import type { CapexCalcResult, CapexProject } from '@/lib/types/capex.types'
import { INVESTOR_OPEX_ESCALATION_PCT } from '@/lib/capex/calculations'

const C={navy:[31,42,68] as const,green:[92,184,0] as const,light:[244,246,249] as const,line:[221,226,234] as const,grid:[237,240,245] as const,muted:[107,116,132] as const,white:[255,255,255] as const}
const n0=new Intl.NumberFormat('de-DE',{maximumFractionDigits:0})
const n1=new Intl.NumberFormat('de-DE',{minimumFractionDigits:1,maximumFractionDigits:1})
const n2=new Intl.NumberFormat('de-DE',{minimumFractionDigits:2,maximumFractionDigits:2})

async function imageData(url:string){try{const r=await fetch(url);if(!r.ok)return null;const b=await r.blob();return await new Promise<string|null>(resolve=>{const f=new FileReader();f.onload=()=>resolve(typeof f.result==='string'?f.result:null);f.onerror=()=>resolve(null);f.readAsDataURL(b)})}catch{return null}}

export async function createCapexReport(project:CapexProject,calc:CapexCalcResult){
  const {default:jsPDF}=await import('jspdf')
  const d=new jsPDF({unit:'mm',format:'a4',orientation:'portrait',compress:true})
  const M=18,W=174,name=project.projektname||project.calculationName||'Projekt',[logo,hero]=await Promise.all([imageData('/ema-logo-transparent.png'),imageData('/hero-dashboard.png')])
  d.setProperties({title:`CAPEX-Kalkulation ${name}`,author:'EMA Enterprise GmbH',subject:'CAPEX-Kalkulation',creator:'EMA Intelligence'})
  const txt=(c:readonly[number,number,number])=>d.setTextColor(...c),fill=(c:readonly[number,number,number])=>d.setFillColor(...c),draw=(c:readonly[number,number,number])=>d.setDrawColor(...c)
  const sec=(t:string,y:number)=>{txt(C.navy);d.setFont('helvetica','bold');d.setFontSize(8);d.text(t.toUpperCase(),M,y);draw(C.green);d.setLineWidth(1.2);d.line(M,y+2.2,M+14,y+2.2);draw(C.line);d.setLineWidth(.35);d.line(M+17,y+2.2,M+W,y+2.2)}
  const foot=(p:number)=>{draw(C.line);d.setLineWidth(.45);d.line(M,281,M+W,281);txt(C.muted);d.setFont('helvetica','normal');d.setFontSize(6.8);d.text('EMA Enterprise GmbH · Gabriel-von-Seidl-Str. 56 · 67550 Worms · unluer@ema-enterprise.de',M,286);d.text(`Investor-Basis vor Steuern/Finanzierung · OPEX +${n1.format(INVESTOR_OPEX_ESCALATION_PCT)} % p.a. · kein Restwert.`,M,290.2);txt(C.navy);d.setFont('helvetica','bold');d.setFontSize(7.5);d.text(`Seite ${p} / 2`,M+W,288.2,{align:'right'})}
  const addHero=()=>{fill(C.navy);d.rect(0,0,210,50,'F');if(hero)d.addImage(hero,'PNG',72,0,138,50,'EMA_CAPEX_HERO','FAST');fill(C.navy);d.rect(0,0,72,50,'F');d.triangle(68,0,100,0,68,50,'F');fill(C.green);d.rect(0,50,210,1.4,'F');if(logo)d.addImage(logo,'PNG',M,12.5,19.7,9.5,undefined,'FAST');else{txt(C.white);d.setFont('helvetica','bold');d.setFontSize(15);d.text('EMA',M,20)}txt([169,179,198]);d.setFont('helvetica','normal');d.setFontSize(7);d.text('EMA ENTERPRISE GMBH',43,18.6);d.text('EMA INTELLIGENCE',192,18.6,{align:'right'});txt(C.white);d.setFont('helvetica','bold');d.setFontSize(22);d.text('CAPEX-KALKULATION',M,32);txt(C.green);d.setFont('helvetica','normal');d.setFontSize(11);d.text(d.splitTextToSize(name,116)[0],M,40)}
  const legalNote=()=>{const note='Diese CAPEX-Kalkulation ist eine unverbindliche, indikative Modellrechnung auf Basis der eingegebenen Daten und getroffenen Annahmen. Sie stellt weder ein verbindliches Angebot noch eine Investitions-, Finanzierungs-, Steuer- oder Rechtsberatung dar. Tatsächliche Kosten, Erträge und Renditen können abweichen. Sämtliche Angaben sind vom Empfänger eigenständig zu prüfen. Eine Garantie für das Eintreten der dargestellten Ergebnisse wird nicht übernommen. Im Übrigen gelten die gesetzlichen Haftungsregelungen.';fill(C.light);d.roundedRect(M,263.5,W,15.5,1.6,1.6,'F');fill(C.green);d.rect(M,263.5,1.4,15.5,'F');txt(C.navy);d.setFont('helvetica','bold');d.setFontSize(5.8);d.text('WICHTIGER HINWEIS',M+4.5,267.1);txt(C.muted);d.setFont('helvetica','normal');d.setFontSize(5.2);d.text(d.splitTextToSize(note,W-9),M+4.5,270,{lineHeightFactor:1.08})}

  addHero()

  sec('Projektdaten',64)
  const fields=[['Kalkulation',project.calculationName,2],['Projekttyp','Photovoltaik',1],['Erstellungsdatum',new Intl.DateTimeFormat('de-DE').format(new Date()),1],['Anlagenleistung',`${n2.format(project.anlagenleistungKwp)} kWp`,1],['Spezifischer Ertrag',`${n2.format(project.spezErtragKwhKwp)} kWh/kWp`,1],['Strompreis',`${n2.format(project.strompreisEurKwh*100)} ct/kWh`,1],['Pachtdauer',project.pachtdauerJahre>0?`${n1.format(project.pachtdauerJahre)} Jahre`:'',1]] as const
  let slot=0;for(const [label,value,slots] of fields){if(value===null||value===undefined||value==='')continue;if(slot%4+slots>4)slot+=4-slot%4;const row=Math.floor(slot/4),col=slot%4,x=M+col*43.5,y=72+row*13;txt(C.muted);d.setFont('helvetica','normal');d.setFontSize(6.6);d.text(label.toUpperCase(),x,y);txt(C.navy);d.setFont('helvetica','bold');d.setFontSize(9.2);const max=slots*43.5-4,s=String(value);d.text(d.getTextWidth(s)<=max?s:`${s.slice(0,Math.max(4,Math.floor(s.length*.72)))}…`,x,y+4.6);slot+=slots}

  sec('Kennzahlen',104)
  const cards=[['Gesamt-CAPEX',`${n0.format(calc.totalCapex)} EUR`,'Investitionsvolumen'],['Spez. Investitionskosten',`${n2.format(calc.specificCapex)} EUR/kWp`,`bezogen auf ${n2.format(project.anlagenleistungKwp)} kWp`],['Projekt-IRR (20 Jahre)',calc.irr==null?'':`${n1.format(calc.irr*100)} %`,'vor Steuern und Finanzierung'],['NPV',`${n0.format(calc.npv)} EUR`,`bei WACC ${n1.format(project.waccPct)} %`],['Statische Amortisation',calc.staticPayback==null?'':`${n1.format(calc.staticPayback)} Jahre`,'CAPEX / Cashflow Jahr 1'],['Diskontierte Amortisation',calc.dynPayback==null?'':`${n1.format(calc.dynPayback)} Jahre`,'diskontiert mit WACC']].filter(x=>x[1])
  cards.forEach((c,i)=>{const x=M+(i%3)*59.7,y=113+Math.floor(i/3)*34,inv=i===0;fill(inv?C.navy:C.light);d.roundedRect(x,y,54.7,29,2.2,2.2,'F');fill(C.green);d.rect(x,y,1.6,29,'F');txt(inv?[169,179,198]:C.muted);d.setFont('helvetica','bold');d.setFontSize(6.8);d.text(c[0].toUpperCase(),x+5,y+7);txt(inv?C.white:C.navy);d.setFontSize(c[1].length>20?12.2:15);d.text(c[1],x+5,y+16.5);if(c[2]){txt(inv?C.green:C.muted);d.setFont('helvetica','normal');d.setFontSize(7);d.text(d.splitTextToSize(c[2],45)[0],x+5,y+24.5)}})

  sec('Komponentenbasis',181)
  const modulePricing=project.componentPricing.module,inverterPricing=project.componentPricing.inverter
  const inverterLabel=project.componentPricing.inverterMode==='hybrid'?'Hybrid-Wechselrichter':'Standard-Wechselrichter'
  const dateLabel=(value:string)=>{if(!value)return 'manuell';const date=new Date(value);return Number.isNaN(date.getTime())?value:new Intl.DateTimeFormat('de-DE').format(date)}
  const moduleLine=modulePricing.model
    ? `${modulePricing.manufacturer} · ${modulePricing.model} · ${n0.format(calc.moduleCount)} Stk. · ${n2.format(project.preisProModul)} EUR/Stk. · Stand ${dateLabel(modulePricing.priceDate)}`
    : 'Module: manuelle Eingabe'
  const inverterLine=inverterPricing.model
    ? `${inverterPricing.manufacturer} · ${inverterPricing.model} · ${n0.format(project.wrAnzahl)} Stk. · ${n2.format(project.wrEinzelpreis)} EUR/Stk. · Stand ${dateLabel(inverterPricing.priceDate)}`
    : `${inverterLabel}: manuelle Eingabe`
  txt(C.navy);d.setFont('helvetica','bold');d.setFontSize(6.6);d.text('MODULE',M,188);d.text(inverterLabel.toUpperCase(),M+88,188)
  txt(C.muted);d.setFont('helvetica','normal');d.setFontSize(6.2);d.text(d.splitTextToSize(moduleLine,82)[0],M,192);d.text(d.splitTextToSize(inverterLine,82)[0],M+88,192)

  sec('Kumulierter Cashflow',201)
  const x0=38,y0=211,cw=154,ch=40,values=calc.years.slice(0,21).map(r=>r.cum),min=Math.min(...values,0),max=Math.max(...values,0),span=Math.max(max-min,1),yf=(v:number)=>y0+ch-((v-min)/span)*ch,xf=(i:number)=>x0+(i/Math.max(values.length-1,1))*cw
  for(let i=0;i<5;i++){const q=i/4,v=max-q*span,y=y0+q*ch;draw(C.grid);d.setLineWidth(.35);d.line(x0,y,x0+cw,y);txt(C.muted);d.setFont('helvetica','normal');d.setFontSize(6.4);d.text(`${n1.format(v/1e6)} Mio.`,x0-2.5,y+1.8,{align:'right'})}
  const zy=yf(0);draw(C.navy);d.setLineWidth(.8);d.line(x0,zy,x0+cw,zy);draw(C.green);d.setLineWidth(1.8);values.forEach((v,i)=>{if(i)d.line(xf(i-1),yf(values[i-1]),xf(i),yf(v))})
  const bi=values.findIndex((v,i)=>i>0&&v>=0);if(bi>0){const a=values[bi-1],b=values[bi],f=b===a?0:(-a)/(b-a),year=bi-1+f,bx=xf(bi-1+f),label=`Break-even Jahr ${n1.format(year)} (nominal)`;draw(C.navy);d.setLineDashPattern([2,2],0);d.setLineWidth(.55);d.line(bx,y0+ch,bx,zy);d.setLineDashPattern([],0);fill(C.navy);d.circle(bx,zy,1.5,'F');fill(C.white);d.circle(bx,zy,.65,'F');const lw=Math.min(56,Math.max(39,d.getTextWidth(label)+6)),lx=Math.min(192-lw,Math.max(18,bx-lw/2));fill(C.navy);d.roundedRect(lx,zy-10,lw,6,1.2,1.2,'F');txt(C.white);d.setFont('helvetica','bold');d.setFontSize(7.2);d.text(label,lx+lw/2,zy-6,{align:'center'})}
  txt(C.muted);d.setFont('helvetica','normal');d.setFontSize(6.4);for(let i=0;i<values.length;i+=2)d.text(`J${i}`,xf(i),y0+ch+5,{align:'center'});d.text('Betriebsjahr, nominal',x0+cw/2,y0+ch+9.5,{align:'center'});if(values.length>1){txt(C.green);d.setFont('helvetica','bold');d.setFontSize(7.2);d.text(`${n1.format(values.at(-1)!/1e6)} Mio. EUR`,x0+cw,Math.max(y0+4,yf(values.at(-1)!)-2.5),{align:'right'})}

  d.addPage();addHero();const pos=calc.positions.filter(r=>r.cost>0),compact=pos.length>8,rowH=compact?6.5:9,totalH=compact?11:13
  sec('CAPEX-Positionen',64);const ty=74;fill(C.navy);d.rect(M,ty,W,7.5,'F');txt(C.white);d.setFont('helvetica','bold');d.setFontSize(7.2);d.text('POSITION',M+3,ty+4.9);d.text('KOSTEN (EUR)',M+W*.62,ty+4.9,{align:'right'});d.text('EUR/KWP',M+W*.82,ty+4.9,{align:'right'});d.text('ANTEIL',M+W-3,ty+4.9,{align:'right'})
  let ry=ty+7.5;pos.forEach((p,i)=>{const baseline=compact?4.4:5.9;if(i%2){fill(C.light);d.rect(M,ry,W,rowH,'F')}txt(C.navy);d.setFont('helvetica','normal');d.setFontSize(compact?7.4:9);d.text(p.name,M+3,ry+baseline);d.text(n0.format(p.cost),M+W*.62,ry+baseline,{align:'right'});txt(C.muted);d.text(n2.format(p.eurPerKwp),M+W*.82,ry+baseline,{align:'right'});txt(C.navy);d.setFont('helvetica','bold');d.setFontSize(compact?7.2:8.4);d.text(`${n1.format(p.share*100)} %`,M+W-3,ry+baseline,{align:'right'});draw(C.line);d.setLineWidth(.3);d.line(M,ry+rowH,M+W,ry+rowH);ry+=rowH})
  fill(C.navy);d.rect(M,ry,W,totalH,'F');fill(C.green);d.rect(M,ry,1.6,totalH,'F');txt(C.white);d.setFont('helvetica','bold');d.setFontSize(compact?9:10);d.text('GESAMT-CAPEX',M+4.5,ry+(compact?7:8.2));d.setFontSize(compact?10.5:12);d.text(n0.format(calc.totalCapex),M+W*.62,ry+(compact?7:8.2),{align:'right'});txt(C.green);d.setFontSize(compact?8:9);d.text(`${n2.format(calc.specificCapex)} EUR/kWp`,M+W*.82,ry+(compact?7:8.2),{align:'right'});txt(C.white);d.text('100,0 %',M+W-3,ry+(compact?7:8.2),{align:'right'})
  const sortedPos=[...pos].sort((a,b)=>b.cost-a.cost),chartPos=sortedPos.slice(0,4).map(p=>({name:p.name,cost:p.cost,share:p.share})),otherCost=sortedPos.slice(4).reduce((sum,p)=>sum+p.cost,0);if(otherCost>0&&calc.totalCapex>0)chartPos.push({name:'Weitere Positionen',cost:otherCost,share:otherCost/calc.totalCapex});const chartColors=[C.navy,C.green,[59,130,246] as const,[20,184,166] as const,[148,163,184] as const],cy=ry+totalH+8;sec('CAPEX-Verteilung',cy);let cx=M;chartPos.forEach((p,i)=>{const segment=W*p.share;fill(chartColors[i]);d.rect(cx,cy+6,segment,6,'F');cx+=segment});chartPos.forEach((p,i)=>{const col=i%2,row=Math.floor(i/2),x=M+col*88,y=cy+18+row*6;fill(chartColors[i]);d.rect(x,y-3.2,3,3,'F');txt(C.muted);d.setFont('helvetica','normal');d.setFontSize(6.5);d.text(d.splitTextToSize(`${p.name} · ${n1.format(p.share*100)} %`,78)[0],x+5,y-0.5)})
  const ey=cy+38;sec('Wirtschaftlichkeit',ey);const eco=[['Ertrag Jahr 1',`${n0.format(calc.energyY1/1000)} MWh`],['Erlös Jahr 1',`${n0.format(calc.revenueY1)} EUR`],['OPEX Jahr 1',`${n0.format(calc.opexY1)} EUR`],['Netto-Cashflow Jahr 1',`${n0.format(calc.ncfY1)} EUR`],['Projekt-IRR (20 Jahre)',calc.irr==null?'':`${n1.format(calc.irr*100)} %`],['NPV',`${n0.format(calc.npv)} EUR`],['Statische Amortisation',calc.staticPayback==null?'':`${n1.format(calc.staticPayback)} Jahre`],['Diskontierte Amortisation',calc.dynPayback==null?'':`${n1.format(calc.dynPayback)} Jahre`],['WACC',`${n1.format(project.waccPct)} %`],['Erlössteigerung',`${n1.format(project.strompreissteigerungPct)} % p.a.`]].filter(x=>x[1]);eco.forEach((e,i)=>{const row=Math.floor(i/2),col=i%2,x=M+col*90,y=ey+9+row*8.6;if(row%2===1&&col===0){fill(C.light);d.rect(M,y-5.6,W,8.6,'F')}txt(C.muted);d.setFont('helvetica','normal');d.setFontSize(8.6);d.text(e[0],x,y);txt(C.navy);d.setFont('helvetica','bold');d.setFontSize(9.4);d.text(e[1],x+84,y,{align:'right'})})
  d.setPage(1);foot(1);d.setPage(2);legalNote();foot(2);return d.output('blob')
}
