'use server'

import { revalidatePath } from 'next/cache'
import { createClient } from '@/lib/supabase/server'
import { CURRENT_PLAUD_NOTE } from '@/lib/plaud/current-note'
export type PlaudItemStatus='suggested'|'open'|'completed'|'rejected'
async function authDb(){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Nicht angemeldet');return{supabase,user}}
export async function savePlaudItem(input:{externalId:string;kind:'task'|'appointment';title:string;detail?:string;source?:string;status:PlaudItemStatus;dueAt?:string}){const{supabase,user}=await authDb();const{data,error}=await supabase.from('plaud_items').upsert({user_id:user.id,external_id:input.externalId,kind:input.kind,title:input.title,detail:input.detail??null,source:input.source??null,status:input.status,due_at:input.dueAt??null,updated_at:new Date().toISOString()},{onConflict:'user_id,external_id'}).select('id,external_id,kind,title,detail,source,status,due_at').single();if(error)throw error;revalidatePath('/plaud');revalidatePath('/dashboard');revalidatePath('/tasks');revalidatePath('/calendar');return data}
export async function decidePlaudItem(id:string,status:'open'|'rejected'){const{supabase,user}=await authDb();const{data,error}=await supabase.from('plaud_items').update({status,updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',user.id).eq('status','suggested').select('id,external_id,note_external_id,kind,title,detail,source,status,due_at').single();if(error)throw error;revalidatePath('/plaud');revalidatePath('/dashboard');revalidatePath('/tasks');revalidatePath('/calendar');return data}
export async function completePlaudItem(id:string){const{supabase,user}=await authDb();const{error}=await supabase.from('plaud_items').update({status:'completed',updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',user.id);if(error)throw error;revalidatePath('/plaud');revalidatePath('/dashboard');revalidatePath('/tasks');revalidatePath('/calendar')}
export async function deletePlaudItem(id:string){const{supabase,user}=await authDb();const{error}=await supabase.from('plaud_items').delete().eq('id',id).eq('user_id',user.id).eq('status','completed');if(error)throw error;revalidatePath('/plaud');revalidatePath('/dashboard');revalidatePath('/tasks');revalidatePath('/calendar')}
export async function savePlaudNoteTitle(title:string){const clean=title.trim();if(!clean)throw new Error('Titel darf nicht leer sein');const{supabase,user}=await authDb();const{error}=await supabase.from('plaud_notes').upsert({user_id:user.id,external_id:CURRENT_PLAUD_NOTE.externalId,title:clean,recorded_at:CURRENT_PLAUD_NOTE.recordedAt,updated_at:new Date().toISOString()},{onConflict:'user_id,external_id'});if(error)throw error;revalidatePath('/plaud');revalidatePath('/dashboard')}
export async function archivePlaudNote(){const{supabase,user}=await authDb();const now=new Date().toISOString();const{data,error}=await supabase.from('plaud_notes').update({archived_at:now,updated_at:now}).eq('user_id',user.id).eq('external_id',CURRENT_PLAUD_NOTE.externalId).select('id').maybeSingle();if(error)throw error;if(!data){const{error:insertError}=await supabase.from('plaud_notes').insert({user_id:user.id,external_id:CURRENT_PLAUD_NOTE.externalId,title:CURRENT_PLAUD_NOTE.defaultTitle,recorded_at:CURRENT_PLAUD_NOTE.recordedAt,archived_at:now,updated_at:now});if(insertError)throw insertError}revalidatePath('/plaud');revalidatePath('/dashboard');revalidatePath('/archive');revalidatePath('/archive/plaud')}
export async function restorePlaudNote(formData?:FormData){const{supabase,user}=await authDb();const noteId=formData?.get('noteId');let query=supabase.from('plaud_notes').update({archived_at:null,updated_at:new Date().toISOString()}).eq('user_id',user.id);query=typeof noteId==='string'&&noteId?query.eq('id',noteId):query.eq('external_id',CURRENT_PLAUD_NOTE.externalId);const{error}=await query;if(error)throw error;revalidatePath('/plaud');revalidatePath('/dashboard');revalidatePath('/archive');revalidatePath('/archive/plaud')}
export async function archivePlaudNoteById(id:string){const{supabase,user}=await authDb();const now=new Date().toISOString();const{error}=await supabase.from('plaud_notes').update({archived_at:now,updated_at:now}).eq('id',id).eq('user_id',user.id);if(error)throw error;revalidatePath('/plaud');revalidatePath('/dashboard');revalidatePath('/archive');revalidatePath('/archive/plaud')}
export async function savePlaudNoteTitleById(id:string,title:string){const clean=title.trim();if(!clean)throw new Error('Titel darf nicht leer sein');const{supabase,user}=await authDb();const{error}=await supabase.from('plaud_notes').update({title:clean,updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',user.id);if(error)throw error;revalidatePath('/plaud');revalidatePath('/dashboard');revalidatePath('/archive/plaud')}
