'use client'

import { useEffect, useMemo, useState, useTransition } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowLeft, CalendarDays, Check, CheckSquare, Clock3, Eye, FileText, Mic2, Pencil, Printer, Save, ShieldCheck, Sparkles, Trash2, X } from 'lucide-react'
import { completePlaudItem, deletePlaudItem, savePlaudItem, savePlaudNoteTitle } from './actions'

type Suggestion={id:string;type:'Termin'|'Aufgabe';title:string;detail:string;source:string;icon:typeof CalendarDays}
type Stored={id:string;external_id:string;kind:'task'|'appointment';title:string;detail:string|null;source:string|null;status:string}
const initialSuggestions:Suggestion[]=[{id:'followup',type:'Termin',title:'Folgegespräch nach Due Diligence',detail:'26.–29. August 2026',source:'Aus Gespräch abgeleitet',icon:CalendarDays},{id:'nda',type:'Aufgabe',title:'NDA abstimmen und unterzeichnen',detail:'Vor Datenraumfreigabe',source:'Im Gespräch besprochen',icon:CheckSquare},{id:'teaser',type:'Aufgabe',title:'Teaser und Präsentation prüfen',detail:'Projektpaket · 4 Projekte',source:'Im Gespräch besprochen',icon:CheckSquare}]
const sections=[['Überblick','Das Gespräch fokussierte den möglichen Erwerb von vier Projekten für erneuerbare Energien (PV/Wind/Biomasse/Speicher) von Herrn Söth und seinem Team durch ein Multi-Family-Office (MFO) mit starkem PV- und Immobilienhintergrund. Herr Söth verfügt über mehr als 30 Jahre Erfahrung in erneuerbaren Energien und bietet vier Projekte an: eines in Bopfingen ist sofort baureif, drei weitere werden in 2–3 Monaten baureif. Das MFO plant ein Bestandsportfolio von 20–30 Megawatt, ist an reinen Projektrechten interessiert und prüft Paket- vs. Einzelkauf. Schwerpunkte sind Preisrahmen (110.000 € pro Megawatt), Reifegrad und Netzanschlussnähe, Datenraumprüfung, NDA, Kaufvertragsentwürfe und eine zügige Umsetzung.'],['Hintergrund','Anbieter ist Herr Söth mit langjähriger Erfahrung in erneuerbaren Energien. Die deutsche Gesellschaft arbeitet in einer Holding-Struktur mit Hauptholding in den Niederlanden. Käuferseite ist ein Multi-Family-Office mit Fokus auf PV und Immobilien. Besprochen wurden vier Projekte, darunter Bopfingen als sofort baubares Projekt und Erbesdorf mit 6,8 MW. Der Anbieter bevorzugt einen Paketverkauf. Nach NDA sollen Datenräume, technische Informationen und gegebenenfalls ein Kaufvertragsentwurf geprüft werden.'],['Schmerzpunkte','Für eine belastbare Bewertung fehlen teilweise präzise Projektgrößen, Reifegrade, Netzanschlussdetails, Entfernungen zu Umspannwerken, Netzanschlusskosten bzw. Baukostenzuschüsse und vollständige Datenräume. Zusätzlich bestehen unterschiedliche Interessen beim Transaktionsumfang. Gleichzeitig besteht Zeitdruck durch mehrere parallele Prüfstränge.'],['Erwartungen','Ziel ist der Erwerb reiner Projektrechte zu marktgerechten Konditionen, ausgehend von 110.000 € pro Megawatt. Die Projekte sollen nach erfolgreicher technischer und juristischer Due Diligence in ein Bestandsportfolio von 20–30 MW übernommen werden.'],['Weitere Informationen','Der Anbieter ist in München ansässig; Herr Söth befand sich zum Gesprächszeitpunkt in Köln. Die Käuferseite verfügt über einen eigenen EPC und plant Eigenbau sowie langfristiges Halten der Assets. Technische Fragen sollen mit Mario, vertragliche und gesellschaftsrechtliche Themen auch mit Thomas abgestimmt werden.']]
const todos=['NDA zwischen Anbieter und Käufer abstimmen und unterzeichnen – Ziel bis 23.08.2026.','Vollständige strukturierte Datenräume bereitstellen.','Teaser und detaillierte Präsentation übermitteln.','Käuferseitige technische Prüfung bis 27.08.2026 durchführen.','Juristische Prüfung eines Kaufvertragsentwurfs starten.','Preisrange sowie Paket- und Einzelkaufoptionen bewerten.','Folgegespräch nach den DD-Ergebnissen für 26.–29.08.2026 terminieren.','Zahlungs- und Sicherungsmechanismen klären.']
const ai=['Standardisierten Datenraum-Index nutzen und nach NDA vollständig befüllen.','Technical Fact Sheets pro Projekt bereitstellen.','Ein gemeinsames Bewertungs-Template verwenden.','DD-Kickoff mit technischen und vertraglichen Ansprechpartnern durchführen.','Für die noch nicht baureifen Projekte eine Meilenstein- bzw. Escrow-Struktur prüfen.']
const DEFAULT_TITLE='08-20 Kundenberatung: Erwerb von Projekten für erneuerbare Energien'

export default function PlaudPage(){const router=useRouter();const[pending,start]=useTransition();const[suggestions,setSuggestions]=useState(initialSuggestions);const[stored,setStored]=useState<Stored[]>([]);const[title,setTitle]=useState(DEFAULT_TITLE);const[editTitle,setEditTitle]=useState(false);const[message,setMessage]=useState('');const[preview,setPreview]=useState(false);
useEffect(()=>{fetch('/api/plaud/state',{cache:'no-store'}).then(r=>r.ok?r.json():null).then(d=>{if(!d)return;setStored(d.items||[]);if(d.note?.title)setTitle(d.note.title);const handled=new Set((d.items||[]).map((x:Stored)=>x.external_id));setSuggestions(initialSuggestions.filter(x=>!handled.has(x.id)))})},[])
const open=stored.filter(x=>x.status==='open'),done=stored.filter(x=>x.status==='completed');const counts=useMemo(()=>({termine:open.filter(x=>x.kind==='appointment').length,aufgaben:open.filter(x=>x.kind==='task').length}),[open]);
const act=(id:string,accept:boolean)=>{const item=suggestions.find(x=>x.id===id);if(!item)return;start(async()=>{await savePlaudItem({externalId:id,kind:item.type==='Termin'?'appointment':'task',title:item.title,detail:item.detail,source:item.source,status:accept?'open':'rejected'});setSuggestions(x=>x.filter(s=>s.id!==id));if(accept)setStored(x=>[...x,{id:`temp-${id}`,external_id:id,kind:item.type==='Termin'?'appointment':'task',title:item.title,detail:item.detail,source:item.source,status:'open'}]);setMessage(accept?`„${item.title}“ dauerhaft übernommen.`:`„${item.title}“ dauerhaft verworfen.`);router.refresh()})};
const saveTitle=()=>start(async()=>{await savePlaudNoteTitle(title);setEditTitle(false);setMessage('Überschrift gespeichert.');router.refresh()});
return <main className="mx-auto w-full max-w-[1180px] space-y-4 px-4 pb-28 pt-[max(1rem,env(safe-area-inset-top))] md:space-y-6 md:px-6 md:py-8"><header className="flex min-h-14 items-center gap-3 print:hidden"><button onClick={()=>window.history.length>1?router.back():router.push('/dashboard')} className="flex h-12 w-12 items-center justify-center rounded-2xl border bg-white shadow-sm"><ArrowLeft/></button><div><p className="text-[11px] font-extrabold uppercase tracking-[.18em] text-[#5CB800]">EMA Intelligence</p><h1 className="text-3xl font-extrabold text-[#07142F]">PLAUD</h1></div></header>
<section className="rounded-[1.75rem] bg-[#1F2A44] p-5 text-white shadow-lg print:hidden"><div className="flex gap-4"><Mic2 className="text-[#76d22a]"/><div><h2 className="text-xl font-extrabold">Gespräche intelligent weiterverarbeiten</h2><p className="mt-2 text-sm text-white/75">Termine, Aufgaben und vollständige PLAUD-Notizen an einem Ort.</p></div></div></section>{message&&<div className="rounded-2xl bg-[#5CB800]/10 px-4 py-3 text-sm font-bold text-[#2F7D00] print:hidden">{message}</div>}
<div className="grid grid-cols-3 gap-2 print:hidden"><Stat icon={Mic2} label="Aufnahmen" value="1"/><Stat icon={CalendarDays} label="Offene Termine" value={String(counts.termine)}/><Stat icon={CheckSquare} label="Offene Aufgaben" value={String(counts.aufgaben)}/></div>
<section className="rounded-[1.75rem] border bg-white p-5 shadow-sm print:hidden"><p className="text-[11px] font-extrabold uppercase tracking-[.15em] text-[#5CB800]">EMA Vorschläge</p><h2 className="mt-1 text-xl font-extrabold text-[#07142F]">{suggestions.length?`${suggestions.length} Elemente prüfen`:'Alles geprüft'}</h2><div className="mt-5 space-y-3">{suggestions.map(item=><Item key={item.id} item={item} disabled={pending} onAct={act}/>)}</div></section>
{open.length>0&&<section className="rounded-[1.75rem] border bg-white p-5 shadow-sm print:hidden"><h2 className="text-xl font-extrabold text-[#07142F]">Übernommen</h2><div className="mt-4 space-y-3">{open.map(x=><article key={x.external_id} className="rounded-2xl border p-4"><b>{x.title}</b><p className="text-sm text-slate-500">{x.detail}</p><button disabled={pending} onClick={()=>start(async()=>{const real=stored.find(s=>s.external_id===x.external_id);if(!real||real.id.startsWith('temp-')){location.reload();return}await completePlaudItem(real.id);setStored(s=>s.map(v=>v.id===real.id?{...v,status:'completed'}:v));router.refresh()})} className="mt-3 rounded-xl bg-[#5CB800] px-4 py-2 font-bold text-white"><Check className="mr-1 inline h-4 w-4"/>Erledigt</button></article>)}</div></section>}
{done.length>0&&<section className="rounded-[1.75rem] border bg-white p-5 shadow-sm print:hidden"><h2 className="text-xl font-extrabold text-[#07142F]">Erledigt</h2><div className="mt-4 space-y-3">{done.map(x=><article key={x.id} className="flex items-center justify-between gap-3 rounded-2xl bg-slate-50 p-4"><div><b className="text-slate-500 line-through">{x.title}</b><p className="text-xs text-slate-400">Erledigt</p></div><button disabled={pending} onClick={()=>start(async()=>{await deletePlaudItem(x.id);setStored(s=>s.filter(v=>v.id!==x.id));router.refresh()})} className="rounded-xl border bg-white p-3 text-red-600" aria-label="Erledigten Eintrag löschen"><Trash2 className="h-5 w-5"/></button></article>)}</div></section>}
<section className="rounded-[1.75rem] border bg-white p-5 shadow-sm print:hidden"><div className="flex gap-3"><FileText className="h-7 w-7 text-[#2F8A00]"/><div className="min-w-0 flex-1"><p className="text-[11px] font-extrabold uppercase tracking-[.15em] text-[#5CB800]">PLAUD Notiz</p>{editTitle?<div className="mt-2 flex gap-2"><input value={title} onChange={e=>setTitle(e.target.value)} className="min-w-0 flex-1 rounded-xl border px-3 py-2 font-bold"/><button disabled={pending||!title.trim()} onClick={saveTitle} className="rounded-xl bg-[#5CB800] px-3 text-white"><Save/></button></div>:<div className="flex items-start gap-2"><h2 className="mt-1 flex-1 text-lg font-extrabold text-[#07142F]">{title}</h2><button onClick={()=>setEditTitle(true)} className="mt-1 rounded-lg p-2"><Pencil className="h-4 w-4"/></button></div>}<p className="mt-1 text-xs text-slate-400">20.08.2026 · 13:32</p></div></div><p className="mt-5 line-clamp-4 text-sm leading-relaxed text-slate-600">{sections[0][1]}</p><button onClick={()=>setPreview(true)} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-[#1F2A44] py-3 font-extrabold text-white"><Eye/>PDF-Vorschau</button></section>
<section className="rounded-[1.75rem] border bg-white p-5 shadow-sm print:hidden"><div className="flex gap-3"><ShieldCheck className="text-[#2F8A00]"/><div><h2 className="font-extrabold">PLAUD <span className="inline-block h-3 w-3 rounded-full bg-slate-300"/></h2><p className="text-sm text-slate-600">Verbindung wird eingerichtet</p></div></div><div className="mt-5 rounded-2xl bg-slate-50 px-4 py-3 text-sm font-semibold text-slate-500"><Sparkles className="mr-2 inline h-4 w-4"/>PLAUD-Integration vorbereitet</div></section>
{preview&&<div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/70 p-3 print:static print:bg-white print:p-0"><div className="mx-auto max-w-[850px]"><div className="sticky top-2 z-10 mb-3 flex gap-2 rounded-2xl bg-white p-2 shadow-xl print:hidden"><button onClick={()=>setPreview(false)} className="flex-1 rounded-xl border py-3 font-bold"><X className="mr-2 inline h-4 w-4"/>Schließen</button><button onClick={()=>window.print()} className="flex-1 rounded-xl bg-[#5CB800] py-3 font-extrabold text-white"><Printer className="mr-2 inline h-4 w-4"/>PDF sichern</button></div><article className="plaud-pdf min-h-[1120px] bg-white p-8 text-[#1F2A44] shadow-2xl md:p-14"><div className="border-b-4 border-[#5CB800] pb-6"><p className="text-xs font-extrabold uppercase tracking-[.2em] text-[#5CB800]">EMA Enterprise GmbH · PLAUD Gesprächsnotiz</p><h1 className="mt-4 text-3xl font-extrabold text-[#07142F]">{title}</h1><p className="mt-3 text-sm text-slate-500">20. August 2026 · 13:32 Uhr</p></div>{sections.map(([h,t])=><section key={h} className="mt-7 break-inside-avoid"><h2 className="text-xl font-extrabold text-[#07142F]">{h}</h2><p className="mt-2 text-sm leading-7 text-slate-700">{t}</p></section>)}<section className="mt-7"><h2 className="text-xl font-extrabold">To-do-Liste</h2><ul className="mt-3 space-y-2">{todos.map(x=><li key={x} className="text-sm">☐ {x}</li>)}</ul></section><section className="mt-7 rounded-2xl bg-slate-50 p-5"><h2 className="text-xl font-extrabold">Vorschläge der PLAUD KI</h2><ol className="mt-3 list-decimal space-y-2 pl-5">{ai.map(x=><li key={x} className="text-sm">{x}</li>)}</ol></section></article></div></div>}<style jsx global>{`@media print{body *{visibility:hidden!important}.plaud-pdf,.plaud-pdf *{visibility:visible!important}.plaud-pdf{position:absolute!important;left:0;top:0;width:100%!important;box-shadow:none!important;padding:14mm!important}@page{size:A4;margin:0}}`}</style></main>}
function Item({item,disabled,onAct}:{item:Suggestion;disabled:boolean;onAct:(id:string,a:boolean)=>void}){const Icon=item.icon;return <article className="rounded-2xl border p-4"><div className="flex gap-3"><Icon/><div><span className="text-[10px] font-extrabold uppercase text-slate-400">{item.type}</span><h3 className="font-extrabold">{item.title}</h3><p className="text-sm text-slate-600">{item.detail}</p><p className="mt-2 text-xs text-slate-400"><Clock3 className="mr-1 inline h-3.5 w-3.5"/>{item.source}</p></div></div><div className="mt-4 grid grid-cols-2 gap-2"><button disabled={disabled} onClick={()=>onAct(item.id,false)} className="rounded-xl border py-2.5 font-bold"><X className="mr-1 inline h-4 w-4"/>Verwerfen</button><button disabled={disabled} onClick={()=>onAct(item.id,true)} className="rounded-xl bg-[#5CB800] py-2.5 font-extrabold text-white"><Check className="mr-1 inline h-4 w-4"/>Übernehmen</button></div></article>}
function Stat({icon:Icon,label,value}:{icon:typeof Mic2,label:string,value:string}){return <div className="rounded-2xl border bg-white p-3 shadow-sm"><Icon className="h-5 w-5"/><p className="mt-3 text-[10px] font-extrabold uppercase text-slate-500">{label}</p><p className="mt-1 text-xl font-extrabold">{value}</p></div>}
