'use client'

import { useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowLeft, CalendarDays, Check, CheckSquare, Clock3, Download, Eye, FileText, Mic2, Printer, ShieldCheck, Sparkles, X } from 'lucide-react'

type Suggestion={id:string;type:'Termin'|'Aufgabe';title:string;detail:string;source:string;icon:typeof CalendarDays}
const initialSuggestions:Suggestion[]=[
{id:'followup',type:'Termin',title:'Folgegespräch nach Due Diligence',detail:'26.–29. August 2026',source:'Aus Gespräch abgeleitet',icon:CalendarDays},
{id:'nda',type:'Aufgabe',title:'NDA abstimmen und unterzeichnen',detail:'Vor Datenraumfreigabe',source:'Im Gespräch besprochen',icon:CheckSquare},
{id:'teaser',type:'Aufgabe',title:'Teaser und Präsentation prüfen',detail:'Projektpaket · 4 Projekte',source:'Im Gespräch besprochen',icon:CheckSquare},]

const sections=[
['Überblick','Das Gespräch fokussierte den möglichen Erwerb von vier Projekten für erneuerbare Energien (PV/Wind/Biomasse/Speicher) von Herrn Söth und seinem Team durch ein Multi-Family-Office (MFO) mit starkem PV- und Immobilienhintergrund. Herr Söth verfügt über mehr als 30 Jahre Erfahrung in erneuerbaren Energien und bietet vier Projekte an: eines in Bopfingen ist sofort baureif, drei weitere werden in 2–3 Monaten baureif. Das MFO plant ein Bestandsportfolio von 20–30 Megawatt, ist an reinen Projektrechten interessiert und prüft Paket- vs. Einzelkauf. Schwerpunkte sind Preisrahmen (110.000 € pro Megawatt), Reifegrad und Netzanschlussnähe, Datenraumprüfung, NDA, Kaufvertragsentwürfe und eine zügige Umsetzung.'],
['Hintergrund','Anbieter ist Herr Söth mit langjähriger Erfahrung in erneuerbaren Energien. Die deutsche Gesellschaft arbeitet in einer Holding-Struktur mit Hauptholding in den Niederlanden. Käuferseite ist ein Multi-Family-Office mit Fokus auf PV und Immobilien. Besprochen wurden vier Projekte, darunter Bopfingen als sofort baubares Projekt und Erbesdorf mit 6,8 MW. Der Anbieter bevorzugt einen Paketverkauf. Nach NDA sollen Datenräume, technische Informationen und gegebenenfalls ein Kaufvertragsentwurf geprüft werden.'],
['Schmerzpunkte','Für eine belastbare Bewertung fehlen teilweise präzise Projektgrößen, Reifegrade, Netzanschlussdetails, Entfernungen zu Umspannwerken, Netzanschlusskosten bzw. Baukostenzuschüsse und vollständige Datenräume. Zusätzlich bestehen unterschiedliche Interessen beim Transaktionsumfang: Der Anbieter bevorzugt das Paket aller vier Projekte, während die Käuferseite Risiko und Reifegrad differenziert einpreisen möchte. Gleichzeitig besteht Zeitdruck durch mehrere parallele Prüfstränge.'],
['Erwartungen','Ziel ist der Erwerb reiner Projektrechte zu marktgerechten Konditionen, ausgehend von 110.000 € pro Megawatt. Die Projekte sollen nach erfolgreicher technischer und juristischer Due Diligence in ein Bestandsportfolio von 20–30 MW übernommen werden. Erwartet werden kurzfristig strukturierte Datenräume, klare technische Ansprechpartner, vollständige Projektinformationen und eine wirtschaftlich tragfähige Paketlösung.'],
['Weitere Informationen','Der Anbieter ist in München ansässig; Herr Söth befand sich zum Gesprächszeitpunkt in Köln. Die Käuferseite verfügt über einen eigenen EPC und plant Eigenbau sowie langfristiges Halten der Assets. Technische Fragen sollen mit Mario, vertragliche und gesellschaftsrechtliche Themen auch mit Thomas abgestimmt werden.'],]
const todos=['NDA zwischen Anbieter und Käufer abstimmen und unterzeichnen – Ziel bis 23.08.2026.','Vollständige strukturierte Datenräume mit Netzdistanzen, Netzanschlusskosten/Baukostenzuschüssen, Genehmigungsstatus und technischen Daten bereitstellen.','Teaser und detaillierte Präsentation übermitteln sowie Kontaktdaten von Mario und Thomas weiterleiten.','Käuferseitige technische Prüfung durch das Planungsbüro bis 27.08.2026 durchführen.','Juristische Prüfung eines Kaufvertragsentwurfs starten.','Intern Preisrange von 110.000 € pro MW sowie Paket- und Einzelkaufoptionen bewerten.','Folgegespräch nach den DD-Ergebnissen für 26.–29.08.2026 terminieren.','Zahlungs- und Sicherungsmechanismen für die noch nicht baureifen Projekte klären.']
const ai=['Standardisierten Datenraum-Index nutzen und nach NDA vollständig befüllen.','Technical Fact Sheets pro Projekt mit Standort, Leistung, Reifegrad, Risiken und technischen Eckdaten bereitstellen.','Ein gemeinsames Bewertungs-Template verwenden, um Rückfragen und Preisfindung zu beschleunigen.','DD-Kickoff mit den technischen und vertraglichen Ansprechpartnern durchführen.','Für die drei noch nicht baureifen Projekte eine Meilenstein- bzw. Escrow-Struktur prüfen.']

export default function PlaudPage(){const router=useRouter();const connected=false;const[suggestions,setSuggestions]=useState(initialSuggestions);const[accepted,setAccepted]=useState<string[]>([]);const[message,setMessage]=useState('');const[preview,setPreview]=useState(false);const counts=useMemo(()=>({termine:suggestions.filter(x=>x.type==='Termin').length,aufgaben:suggestions.filter(x=>x.type==='Aufgabe').length}),[suggestions]);const goBack=()=>window.history.length>1?router.back():router.push('/dashboard');const act=(id:string,accept:boolean)=>{const item=suggestions.find(x=>x.id===id);if(!item)return;setSuggestions(x=>x.filter(s=>s.id!==id));if(accept)setAccepted(x=>[...x,id]);setMessage(accept?`„${item.title}“ übernommen.`:`„${item.title}“ verworfen.`)};return <main className="mx-auto w-full max-w-[1180px] space-y-4 px-4 pb-28 pt-[max(1rem,env(safe-area-inset-top))] md:space-y-6 md:px-6 md:py-8">
<header className="flex min-h-14 items-center gap-3 print:hidden"><button onClick={goBack} className="flex h-12 w-12 items-center justify-center rounded-2xl border bg-white shadow-sm"><ArrowLeft className="h-6 w-6"/></button><div><p className="text-[11px] font-extrabold uppercase tracking-[.18em] text-[#5CB800]">EMA Intelligence</p><div className="flex items-center gap-2"><h1 className="text-3xl font-extrabold text-[#07142F]">PLAUD</h1><span className={`h-3 w-3 rounded-full ${connected?'bg-[#5CB800]':'bg-slate-300'}`}/></div></div></header>
<section className="rounded-[1.75rem] bg-[#1F2A44] p-5 text-white shadow-lg print:hidden"><div className="flex gap-4"><Mic2 className="h-7 w-7 text-[#76d22a]"/><div><h2 className="text-xl font-extrabold">Gespräche intelligent weiterverarbeiten</h2><p className="mt-2 text-sm text-white/75">Termine, Aufgaben und vollständige PLAUD-Notizen an einem Ort.</p></div></div></section>
{message&&<div className="rounded-2xl bg-[#5CB800]/10 px-4 py-3 text-sm font-bold text-[#2F7D00] print:hidden">{message}</div>}
<div className="grid grid-cols-3 gap-2 print:hidden"><Stat icon={Mic2} label="Aufnahmen" value="1"/><Stat icon={CalendarDays} label="Termine" value={String(counts.termine)}/><Stat icon={CheckSquare} label="Aufgaben" value={String(counts.aufgaben)}/></div>
<section className="rounded-[1.75rem] border bg-white p-5 shadow-sm print:hidden"><p className="text-[11px] font-extrabold uppercase tracking-[.15em] text-[#5CB800]">EMA Vorschläge</p><h2 className="mt-1 text-xl font-extrabold text-[#07142F]">{suggestions.length?`${suggestions.length} Elemente prüfen`:'Alles geprüft'}</h2><div className="mt-5 space-y-3">{suggestions.map(({id,type,title,detail,source,icon:Icon})=><article key={id} className="rounded-2xl border p-4"><div className="flex gap-3"><Icon className="h-5 w-5"/><div><span className="text-[10px] font-extrabold uppercase text-slate-400">{type}</span><h3 className="font-extrabold text-[#07142F]">{title}</h3><p className="text-sm text-slate-600">{detail}</p><p className="mt-2 flex gap-1 text-xs text-slate-400"><Clock3 className="h-3.5 w-3.5"/>{source}</p></div></div><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={()=>act(id,false)} className="rounded-xl border py-2.5 font-bold"><X className="mr-1 inline h-4 w-4"/>Verwerfen</button><button onClick={()=>act(id,true)} className="rounded-xl bg-[#5CB800] py-2.5 font-extrabold text-white"><Check className="mr-1 inline h-4 w-4"/>Übernehmen</button></div></article>)}</div></section>
<section className="rounded-[1.75rem] border bg-white p-5 shadow-sm print:hidden"><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><FileText className="h-7 w-7 text-[#2F8A00]"/><div><p className="text-[11px] font-extrabold uppercase tracking-[.15em] text-[#5CB800]">PLAUD Notiz</p><h2 className="mt-1 text-lg font-extrabold text-[#07142F]">08-20 Kundenberatung: Erwerb von Projekten für erneuerbare Energien</h2><p className="mt-1 text-xs text-slate-400">20.08.2026 · 13:32</p></div></div></div><p className="mt-5 line-clamp-4 text-sm leading-relaxed text-slate-600">{sections[0][1]}</p><button onClick={()=>setPreview(true)} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-[#1F2A44] py-3 font-extrabold text-white"><Eye className="h-5 w-5"/>PDF-Vorschau</button></section>
<section className="rounded-[1.75rem] border bg-white p-5 shadow-sm print:hidden"><div className="flex gap-3"><ShieldCheck className="h-6 w-6 text-[#2F8A00]"/><div><h2 className="font-extrabold text-[#07142F]">PLAUD <span className="inline-block h-3 w-3 rounded-full bg-slate-300"/></h2><p className="text-sm text-slate-600">Verbindung wird eingerichtet</p></div></div><div className="mt-5 rounded-2xl bg-slate-50 px-4 py-3 text-sm font-semibold text-slate-500"><Sparkles className="mr-2 inline h-4 w-4"/>PLAUD-Integration vorbereitet</div></section>
{preview&&<div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/70 p-3 print:static print:bg-white print:p-0"><div className="mx-auto max-w-[850px]"><div className="sticky top-2 z-10 mb-3 flex gap-2 rounded-2xl bg-white p-2 shadow-xl print:hidden"><button onClick={()=>setPreview(false)} className="flex-1 rounded-xl border py-3 font-bold"><X className="mr-2 inline h-4 w-4"/>Schließen</button><button onClick={()=>window.print()} className="flex-1 rounded-xl bg-[#5CB800] py-3 font-extrabold text-white"><Printer className="mr-2 inline h-4 w-4"/>PDF sichern</button></div><article className="plaud-pdf min-h-[1120px] bg-white p-8 text-[#1F2A44] shadow-2xl md:p-14"><div className="border-b-4 border-[#5CB800] pb-6"><p className="text-xs font-extrabold uppercase tracking-[.2em] text-[#5CB800]">EMA Enterprise GmbH · PLAUD Gesprächsnotiz</p><h1 className="mt-4 text-3xl font-extrabold text-[#07142F]">Kundenberatung: Erwerb von Projekten für erneuerbare Energien</h1><p className="mt-3 text-sm text-slate-500">20. August 2026 · 13:32 Uhr</p></div>{sections.map(([h,t])=><section key={h} className="mt-7 break-inside-avoid"><h2 className="text-xl font-extrabold text-[#07142F]">{h}</h2><p className="mt-2 whitespace-pre-line text-sm leading-7 text-slate-700">{t}</p></section>)}<section className="mt-7"><h2 className="text-xl font-extrabold text-[#07142F]">To-do-Liste</h2><ul className="mt-3 space-y-2">{todos.map(x=><li key={x} className="text-sm leading-6 text-slate-700">☐ {x}</li>)}</ul></section><section className="mt-7 rounded-2xl bg-slate-50 p-5"><h2 className="text-xl font-extrabold text-[#07142F]">Vorschläge der PLAUD KI</h2><ol className="mt-3 list-decimal space-y-2 pl-5">{ai.map(x=><li key={x} className="text-sm leading-6 text-slate-700">{x}</li>)}</ol></section><footer className="mt-10 border-t pt-4 text-xs text-slate-400">Quelle: PLAUD · Vollständige Gesprächsnotiz in EMA zur Dokumentation aufbereitet</footer></article></div></div>}
<style jsx global>{`@media print{body *{visibility:hidden!important}.plaud-pdf,.plaud-pdf *{visibility:visible!important}.plaud-pdf{position:absolute!important;left:0;top:0;width:100%!important;box-shadow:none!important;padding:14mm!important}@page{size:A4;margin:0}}`}</style></main>}
function Stat({icon:Icon,label,value}:{icon:typeof Mic2,label:string,value:string}){return <div className="rounded-2xl border bg-white p-3 shadow-sm"><Icon className="h-5 w-5"/><p className="mt-3 text-[10px] font-extrabold uppercase text-slate-500">{label}</p><p className="mt-1 text-xl font-extrabold text-[#07142F]">{value}</p></div>}
