'use client'

import { useEffect, useState } from 'react'
import { BellRing } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'

function decodeKey(value: string): ArrayBuffer { const padding = '='.repeat((4 - value.length % 4) % 4); const base64 = (value + padding).replace(/-/g, '+').replace(/_/g, '/'); const bytes = Uint8Array.from(atob(base64), c => c.charCodeAt(0)); return bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) }
export function PushControls() {
 const [supported,setSupported]=useState(false),[active,setActive]=useState(false),[message,setMessage]=useState('')
 useEffect(()=>{setSupported('serviceWorker' in navigator && 'PushManager' in window && 'Notification' in window); navigator.serviceWorker?.ready.then(async r=>setActive(Boolean(await r.pushManager.getSubscription()))).catch(()=>undefined)},[])
 async function enable(){setMessage('');if(!supported)return setMessage('Push wird auf diesem Gerät nicht unterstützt.');const key=process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY;if(!key)return setMessage('Push ist serverseitig noch nicht konfiguriert.');if(await Notification.requestPermission()!=='granted')return setMessage('Mitteilungen wurden nicht erlaubt.');const registration=await navigator.serviceWorker.ready;let subscription=await registration.pushManager.getSubscription();subscription??=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:decodeKey(key)});const json=subscription.toJSON(),supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user||!json.endpoint||!json.keys?.p256dh||!json.keys?.auth)return setMessage('Push-Registrierung konnte nicht gespeichert werden.');const {error}=await supabase.from('ema_push_subscriptions').upsert({user_id:user.id,endpoint:json.endpoint,p256dh:json.keys.p256dh,auth_key:json.keys.auth,device_label:navigator.userAgent.slice(0,180),last_seen_at:new Date().toISOString()},{onConflict:'user_id,endpoint'});if(error)return setMessage(error.message);setActive(true);setMessage('Erinnerungen sind auf diesem Gerät aktiviert.')}
 async function disable(){const registration=await navigator.serviceWorker.ready,subscription=await registration.pushManager.getSubscription();if(!subscription)return setActive(false);const endpoint=subscription.endpoint;await subscription.unsubscribe();await createClient().from('ema_push_subscriptions').delete().eq('endpoint',endpoint);setActive(false);setMessage('Erinnerungen wurden auf diesem Gerät deaktiviert.')}
 return <section className="rounded-3xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><BellRing className="h-5 w-5"/><h2 className="text-xl font-semibold">iPhone-Erinnerungen</h2></div><p className="mt-2 text-sm text-slate-600">Aktiviere Mitteilungen einmal pro Gerät. Auf dem iPhone funktioniert Web Push mit der zum Home-Bildschirm hinzugefügten EMA-App.</p><button onClick={active?disable:enable} className="mt-4 rounded-xl bg-slate-900 px-4 py-2 font-semibold text-white">{active?'Erinnerungen deaktivieren':'Erinnerungen aktivieren'}</button>{message&&<p className="mt-2 text-sm text-slate-600">{message}</p>}</section>
}
