import type { ProjectListLanguage } from './types';

const englishReplacements: Array<[string, string]> = [
  ['Kuratierte Übersicht von', 'Curated overview of'],
  ['Photovoltaikprojekten', 'photovoltaic projects'],
  ['französischen Regionen mit einer Gesamtleistung von', 'French regions with a total capacity of'],
  ['Alle Projekte werden über EMA Enterprise off-market angeboten; Detailunterlagen und Datenraum stehen nach gegengezeichneter Vertraulichkeitsvereinbarung zur Verfügung.', 'All projects are offered off-market through EMA Enterprise; detailed documentation and data-room access are available after execution of a confidentiality agreement.'],
  ['Alle Projekte werden über EMA Enterprise off-market angeboten;', 'All projects are offered off-market through EMA Enterprise;'],
  ['Detailunterlagen und Datenraum stehen nach gegengezeichneter', 'detailed documentation and data-room access are available after execution of a'],
  ['ausschließlich zur Prüfung durch den benannten Empfänger · kein öffentliches Angebot', 'solely for review by the named recipient · not a public offer'],
  ['PC-Datum älter als 4 Monate (Indiz purgé)', 'Permit date older than 4 months (indication of final permit)'],
  ['Ø Distanz zum Netzverknüpfungspunkt', 'Ø distance to grid connection point'],
  ['Ø Produktionsstunden PVSYST', 'Ø PVSYST full-load hours'],
  ['Regionen mit Projektbestand · Einfärbung nach Leistungsanteil', 'Regions with projects · colour by capacity share'],
  ['Projektstandorte · Markergröße nach Leistung', 'Project locations · marker size by capacity'],
  ['Einzelvorhaben in der Liste', 'Individual assets in the list'],
  ['beantragte Leistung · Ø', 'requested capacity · Ø'],
  ['Leistung = beantragte Leistung („Power asked“), keine bestätigte Netzanschlusskapazität.', 'Capacity = requested capacity (“Power asked”), not confirmed grid-connection capacity.'],
  ['Maßgeblich ist die Kapazitätszusage des Netzbetreibers je Projekt.', 'The grid operator’s confirmed capacity for each project is authoritative.'],
  ['PC-Datum = Datum der Baugenehmigung laut Entwicklerliste.', 'Permit date = building-permit date according to the developer list.'],
  ['Grün hinterlegt', 'Green background'], ['Gelb hinterlegt', 'Yellow background'],
  ['Datum liegt mehr als vier Monate zurück, die Rechtsmittelfrist ist damit rechnerisch abgelaufen (Indiz für purgé, keine Bestätigung).', 'the date is more than four months old, so the appeal period has mathematically expired (indication of a final permit, not confirmation).'],
  ['Datum liegt weniger als vier Monate zurück oder in der Zukunft; diese Projekte sind nicht bau- und finanzierbar.', 'the date is less than four months old or in the future; these projects are not yet construction- and finance-ready.'],
  ['Netz = PS-Distanz laut Liste. Ertrag = Produktionsstunden PVSYST.', 'Grid = PS distance according to the list. Yield = PVSYST full-load hours.'],
  ['Alle Kennzahlen berechnet aus den', 'All metrics calculated from the'],
  ['absteigend nach installierter Leistung', 'descending by installed capacity'],
  ['Anteil an der Gesamtleistung', 'Share of total capacity'],
  ['nach Leistung', 'by capacity'], ['nach PC-Datum', 'by permit date'], ['nach Zieljahr', 'by target year'],
  ['übrige Jahre', 'other years'], ['weitere Regionen', 'other regions'],
  ['Die Liste bündelt', 'The list comprises'], ['französische Photovoltaikprojekte mit einer', 'French photovoltaic projects with a'],
  ['auf rund', 'across approximately'], ['Projektfläche', 'of project area'],
  ['Die Einzelgrößen reichen von', 'Individual project sizes range from'],
  ['bei einem Median von', 'with a median of'],
  ['das Portfolio ist damit sowohl für Einzelankäufe als auch für eine Paketlösung geeignet.', 'making the portfolio suitable for both individual acquisitions and a portfolio transaction.'],
  ['Die durchschnittliche Distanz zum vorgesehenen Netzverknüpfungspunkt beträgt', 'The average distance to the intended grid connection point is'],
  ['die mittleren Produktionsstunden liegen bei', 'average full-load hours are'],
  ['Auf Projekte mit einem PC-Datum, das mehr als vier Monate zurückliegt, entfallen', 'Projects with a permit date older than four months account for'],
  ['der Leistung. Das ist ein Reifeindikator, keine Bestätigung der Bestandskraft – der Nachweis erfolgt projektbezogen über den Genehmigungsbescheid.', 'of capacity. This is a maturity indicator, not confirmation that permits are final; evidence must be verified for each project.'],
  ['Die frühesten Inbetriebnahmen sind für', 'The earliest commissioning dates are scheduled for'],
  ['vorgesehen.', '.'],
  ['Sämtliche Angaben beruhen auf den Unterlagen der jeweiligen Projektentwickler.', 'All information is based on documentation supplied by the respective project developers.'],
  ['Sie ersetzen keine technische, rechtliche oder steuerliche Due Diligence; Netzanschlusszusagen, Flächenverträge, Genehmigungsbescheide und Ertragsgutachten werden im Datenraum projektbezogen bereitgestellt.', 'It does not replace technical, legal or tax due diligence; grid-connection confirmations, land agreements, permits and yield reports are provided for each project in the data room.'],
  ['Gegenzeichnung der Vertraulichkeitsvereinbarung; anschließend Freigabe der projektbezogenen Unterlagen.', 'Execute the confidentiality agreement; project-specific documentation is then released.'],
  ['Auswahl der Projekte nach Größe, Region, Genehmigungsstand und Zeitpunkt der Inbetriebnahme.', 'Select projects by size, region, permit status and commissioning date.'],
  ['Netzanschluss, Flächensicherung, Genehmigung und Ertragsgutachten je Projekt im Datenraum.', 'Review grid connection, land security, permits and yield reports for each project in the data room.'],
  ['Abstimmung von Struktur, Kaufpreismechanik und Zeitplan; danach Exklusivität und SPA-Verhandlung.', 'Agree structure, purchase-price mechanics and timetable, followed by exclusivity and SPA negotiations.'],
  ['Dieses Dokument dient ausschließlich der unverbindlichen Information des benannten Empfängers und stellt kein Angebot, keine Anlageberatung und keine Aufforderung zur Abgabe eines Angebots dar.', 'This document is provided solely for the non-binding information of the named recipient and does not constitute an offer, investment advice or a solicitation to make an offer.'],
  ['Alle Leistungsangaben sind beantragte Leistungen („Power asked“) und stellen weder eine bestätigte Netzanschlusskapazität noch eine zugesicherte Anlagenleistung dar;', 'All capacity figures are requested capacities (“Power asked”) and constitute neither confirmed grid-connection capacity nor guaranteed plant capacity;'],
  ['Angaben zu Leistung, Fläche, Netzdistanz, Genehmigungsstand und Erträgen beruhen auf Informationen Dritter und wurden von EMA Enterprise GmbH nicht abschließend verifiziert.', 'Capacity, area, grid distance, permit status and yield figures are based on third-party information and have not been conclusively verified by EMA Enterprise GmbH.'],
  ['Eine Weitergabe an Dritte ist ohne schriftliche Zustimmung nicht gestattet.', 'Distribution to third parties is prohibited without written consent.'],
  ['Die 8. period war mit', 'The 8th period received'], ['konformer Leistung gegenüber', 'of compliant capacity against a'],
  ['Zielvolumen', 'target volume'], ['Bei einem seit vier Perioden nahezu unveränderten Zuschlagswert von rund', 'With the awarded price remaining almost unchanged for four periods at approximately'],
  ['verlagert sich der Wettbewerb vom Preis auf die Projektreife – ausschlaggebend sind eine vorliegende Baugenehmigung und eine kurze Realisierungsdauer.', 'competition is shifting from price to project maturity; a valid building permit and short delivery period are decisive.'],
  ['Genehmigungsnahe Vorhaben gewinnen dadurch an relativer Attraktivität, besonders auf landwirtschaftlichen Flächen (Cas 2 bis), wo die Begrenzung auf', 'Projects close to permitting therefore become relatively more attractive, particularly on agricultural land (Case 2 bis), where the cap of'],
  ['je period zuletzt rund', 'per period most recently excluded approximately'], ['der konformen Capacity ausgeschlossen hat.', 'of compliant capacity.'],
  ['Das Portfolio eröffnet Investoren einen strukturierten Off-Market-Zugang zu genau diesem Marktumfeld.', 'The portfolio gives investors structured off-market access to this market environment.'],
  ['Die 8. Periode war mit', 'The 8th period received'],
  ['je Periode zuletzt rund', 'per period most recently excluded approximately'],
  ['der konformen Leistung ausgeschlossen hat.', 'of compliant capacity.'],
  ['Agri-PV bei', 'Agrivoltaics at'],
  ['Angegeben ist der gewichtete durchschnittliche Referenzpreis T0 der zur Bezuschlagung vorgeschlagenen Dossiers, nicht indexiert;', 'The stated figure is the non-indexed weighted average T0 reference price of applications proposed for award;'],
  ['die Vergütung erfolgt über 20 Jahre als complément de rémunération und entspricht keiner heutigen Einspeisevergütung.', 'remuneration is paid for 20 years as a complément de rémunération and is not equivalent to a current feed-in tariff.'],
  ['war zum Erstellungsdatum nicht veröffentlicht und ist nicht enthalten.', 'had not been published as of the document date and is not included.'],
  ['Die 9. Periode', 'The 9th period'],
  ['(Cas 2 bis)', '(Case 2 bis)'],
  ['Rapports de synthèse zum Appel d\'offres', 'summary reports for the call for tenders'],
  ['PC erteilt · purgé', 'Permit granted · final'], ['PC erteilt', 'Permit granted'],
  ['PC eingereicht', 'Permit submitted'], ['PC in Vorbereitung', 'Permit in preparation'],
  ['RTB · purgé', 'RTB · final'], ['In Vorbereitung', 'In preparation'],
  ['gelisteten', 'listed'], ['Größtes Projekt', 'Largest project'], ['Kleinstes Projekt', 'Smallest project'],
  ['der Gesamtleistung', 'of total capacity'], ['MWp gesamt', 'MWp total'],
  ['unter 20 MW', 'below 20 MW'], ['ab 50 MW', '50 MW and above'], ['Rang', 'Rank'],
  ['mit PC-Datum, das mehr als vier Monate zurückliegt.', 'with a permit date older than four months.'],
  ['Gesamtleistung von', 'total capacity of'],
  ['Die Einzelgrößen reichen von', 'Individual project sizes range from'],
  ['bei einem Median von', 'with a median of'],
  ['das Portfolio ist damit sowohl für Einzelankäufe als auch für eine Paketlösung geeignet.', 'making the portfolio suitable for both individual acquisitions and a portfolio transaction.'],
  ['Sie ersetzen keine technische, rechtliche oder steuerliche Due Diligence;', 'They do not replace technical, legal or tax due diligence;'],
  ['Netzanschlusszusagen, Flächenverträge, Genehmigungsbescheide und Ertragsgutachten werden im Datenraum projektbezogen bereitgestellt.', 'grid-connection confirmations, land agreements, permits and yield reports are provided for each project in the data room.'],
  ['Ø Netzdistanz', 'Ø grid distance'], ['Ø Produktionsstunden', 'Ø full-load hours'],
  ['Dieses Dokument dient ausschließlich der unverbindlichen Information des benannten Empfängers und stellt kein Angebot, keine Anlageberatung und keine Aufforderung zur', 'This document is provided solely for the non-binding information of the named recipient and does not constitute an offer, investment advice or a solicitation to'],
  ['Abgabe eines Angebots dar.', 'make an offer.'],
  ['Alle Leistungsangaben sind beantragte Leistungen („Power asked“) und stellen weder eine bestätigte Netzanschlusskapazität noch eine', 'All capacity figures are requested capacities (“Power asked”) and constitute neither confirmed grid-connection capacity nor'],
  ['zugesicherte Anlagenleistung dar;', 'guaranteed plant capacity;'],
  ['maßgeblich ist die Kapazitätszusage des Netzbetreibers je Projekt.', 'the grid operator’s confirmed capacity for each project is authoritative.'],
  ['Angaben zu Leistung, Fläche, Netzdistanz, Genehmigungsstand und Erträgen', 'Capacity, area, grid distance, permit status and yield figures'],
  ['beruhen auf Informationen Dritter und wurden von EMA Enterprise GmbH nicht abschließend verifiziert.', 'are based on third-party information and have not been conclusively verified by EMA Enterprise GmbH.'],
  ['Eine Weitergabe an Dritte ist ohne schriftliche Zustimmung nicht gestattet.', 'Distribution to third parties is prohibited without written consent.'],
  ['Detailunterlagen und Datenraum stehen nach', 'detailed documentation and data-room access are available after execution of a'],
  ['gegengezeichneter confidentiality agreement available.', 'signed confidentiality agreement.'],
  ['keine bestätigte Netzanschlusskapazität', 'not confirmed grid-connection capacity'],
  ['Die Einzelgrößen', 'Individual project sizes'], ['reichen von', 'range from'],
  ['bei einem Median von', 'with a median of'], ['das Portfolio ist damit', 'making the portfolio'],
  ['sowohl für Einzelankäufe als auch für eine Paketlösung', 'suitable for both individual acquisitions and a portfolio transaction'],
  ['geeignet.', '.'],
  ['Genehmigungsbescheide und Ertragsgutachten werden im Datenraum', 'permits and yield reports are provided in the data room'],
  ['projektbezogen bereitgestellt.', 'for each project.'],
  ['Dieses Dokument dient ausschließlich der unverbindlichen Information des benannten Empfängers und stellt kein Angebot, keine Anlageberatung und keine Aufforderung zur', 'This document is provided solely for the non-binding information of the named recipient and does not constitute an offer, investment advice or a solicitation to'],
  ['Alle Leistungsangaben sind beantragte Leistungen („Power asked") und stellen weder eine bestätigte', 'All capacity figures are requested capacities (“Power asked”) and constitute neither confirmed'],
  ['noch eine guaranteed plant capacity', 'nor guaranteed plant capacity'],
  ['maßgeblich ist die capacity confirmation des Netzbetreibers je project.', 'the grid operator’s confirmed capacity for each project is authoritative.'],
  ['Angaben zu Capacity, area, Netzdistanz, permit status und yields', 'Capacity, area, grid distance, permit status and yield figures'],
  ['Eine Weitergabe an Dritte ist ohne written consent nicht gestattet.', 'Distribution to third parties is prohibited without written consent.'],
  ['Netzdistanz', 'grid distance'], ['Netzbetreibers', 'grid operator'],
  ['Detailunterlagen', 'Detailed documentation'], ['und Datenraum', 'and data-room access'],
  ['stehen nach', 'are available after'], ['gegengezeichneter', 'execution of a signed'],
  ['Die Einzelgrößen', 'Individual project sizes'], [' MWp bis ', ' MWp to '],
  ['bei einem Median von', 'with a median of'],
  ['sowohl für Einzelankäufe als auch für eine Paketlösung', 'suitable for both individual acquisitions and a portfolio transaction'],
  ['der total capacity', 'of total capacity'],
  ['of project area', 'project area'],
  ['Dieses Dokument dient ausschließlich', 'This document is provided solely'],
  ['der unverbindlichen Information des benannten Empfängers', 'for the non-binding information of the named recipient'],
  ['und stellt kein Angebot', 'and does not constitute an offer'],
  ['keine Anlageberatung', 'no investment advice'], ['keine Aufforderung zur', 'no solicitation to'],
  ['maßgeblich ist die capacity confirmation des grid operator je project.', 'the grid operator’s confirmed capacity for each project is authoritative.'],
  ['Angaben zu Capacity, area, grid distance, permit status und yields', 'Capacity, area, grid distance, permit status and yield figures'],
  ['Eine Weitergabe an Dritte', 'Distribution to third parties'],
  ['ist ohne written consent nicht gestattet.', 'is prohibited without written consent.'],
  ['Januar', 'January'], ['Februar', 'February'], ['März', 'March'], ['April', 'April'],
  ['Mai', 'May'], ['Juni', 'June'], ['Juli', 'July'], ['August', 'August'],
  ['September', 'September'], ['Oktober', 'October'], ['November', 'November'], ['Dezember', 'December'],
  ['zur Prüfung durch den benannten Empfänger', 'for review by the named recipient'],
  ['kein öffentliches Angebot', 'not a public offer'],
  ['Kapazitätszusage', 'capacity confirmation'], ['Netzanschlusskapazität', 'grid-connection capacity'],
  ['Genehmigungsstand', 'permit status'], ['Erträgen', 'yields'], ['Informationen Dritter', 'third-party information'],
  ['nicht abschließend verifiziert', 'not conclusively verified'], ['schriftliche Zustimmung', 'written consent'],
  ['Vertraulichkeitsvereinbarung', 'confidentiality agreement'], ['zur Verfügung', 'available'],
  ['Projekten', 'projects'], ['Projektgrößen', 'project sizes'], ['Projektgröße', 'project size'],
  ['französischen', 'French'], ['davon', 'including'], ['mit einer', 'with a'], ['zurückliegt', 'is older'],
  ['mehr als vier Monate', 'more than four months'], ['Gesamtleistung', 'total capacity'], ['Gesamtfläche', 'total area'],
  ['Fläche', 'area'], ['beantragt', 'requested'], ['Genehmigung', 'permit'], ['Baugenehmigung', 'building permit'],
  ['nicht veröffentlicht', 'not published'], ['nicht enthalten', 'not included'], ['erstellt', 'created'],
  ['lang="de"', 'lang="en"'], ['Vertraulich', 'Confidential'], ['Seite ', 'Page '],
  ['Portfolio-Übersicht', 'Portfolio overview'], ['Projektübersicht', 'Project overview'],
  ['Portfolio-Analyse', 'Portfolio analysis'], ['Marktanalyse · Ausschreibungsergebnisse', 'Market analysis · tender results'],
  ['Frankreich · Marktumfeld &amp; Ausschreibungsanalyse 2026', 'France · market environment &amp; tender analysis 2026'],
  ['Letzte CRE-Runde', 'Latest CRE round'], ['Periode', 'period'], ['Frist', 'Deadline'], ['Ergebnis', 'Result'],
  ['Ø Zuschlagswert', 'Ø awarded price'], ['gewichtetes Mittel', 'weighted average'], ['ggü.', 'vs.'],
  ['Zuschlagsvolumen', 'Awarded volume'], ['Projekte', 'projects'], ['Projekt', 'project'], ['ausgeschrieben', 'tendered'],
  ['Markteinschätzung', 'Market assessment'], ['Sehr attraktiv', 'Very attractive'], ['fach überzeichnet', 'x oversubscribed'],
  ['Vergütung der letzten sechs CRE-Ausschreibungen', 'Remuneration in the last six CRE tenders'],
  ['Gewichteter durchschnittlicher Zuschlagswert der bezuschlagten Dossiers', 'Weighted average awarded price of successful applications'],
  ['Spanne', 'Range'], ['Bezuschlagt insgesamt', 'Total awarded'], ['Agri-PV · Cas 2 bis', 'Agrivoltaics · Case 2 bis'],
  ['unter dem Gesamtschnitt', 'below the overall average'], ['Konform eingereicht', 'Compliant submissions'],
  ['Dossiers auf', 'applications against'], ['Periodendeckel', 'period cap'], ['Deckelbedingt eliminiert', 'Excluded due to cap'],
  ['der konformen Agri-PV-Leistung', 'of compliant agrivoltaic capacity'], ['Regionale Schwerpunkte', 'Regional focus'],
  ['EMA-Projektstandorte', 'EMA project locations'], ['Quelle:', 'Source:'],
  ['Projektstandorte · Markergröße nach Leistung', 'Project locations · marker size by capacity'],
  ['Regionen mit Projektbestand · Einfärbung nach Leistungsanteil', 'Regions with projects · colour by capacity share'],
  ['Projektliste', 'Project list'], ['Dokument-ID', 'Document ID'], ['Erstellungsdatum', 'Creation date'],
  ['Land', 'Country'], ['Technologie', 'Technology'], ['Gesamtleistung', 'Total capacity'],
  ['Einzelvorhaben in der Liste', 'Individual assets in the list'], ['beantragte Leistung', 'requested capacity'],
  ['Regionen', 'regions'], ['führend mit', 'leading with'], ['Fortsetzung', 'continued'], ['Stand', 'as of'],
  ['Département', 'Department'], ['Leistung', 'Capacity'], ['beantragt', 'requested'], ['Netz', 'Grid'],
  ['Fläche', 'Area'], ['Anlagentyp', 'Technology'], ['PC-Datum', 'Permit date'], ['IBN', 'COD'], ['Ziel', 'Target'],
  ['Ertrag', 'Yield'], ['Summe Portfolio', 'Portfolio total'], ['Zwischensumme', 'Subtotal'],
  ['Alle Kennzahlen berechnet aus den', 'All metrics calculated from the'], ['gelisteten projects', 'listed projects'],
  ['Ø Capacity', 'Ø capacity'], ['Größtes project', 'Largest project'], ['Kleinstes project', 'Smallest project'],
  ['Regionale Leistungsverteilung', 'Regional capacity distribution'], ['Leistungsklassen', 'Capacity classes'],
  ['Anteil an der Total capacity', 'Share of total capacity'], ['Genehmigungsstatus', 'Permit status'],
  ['Genehmigungsreife', 'Permit maturity'], ['Transaktionsstruktur', 'Transaction structure'],
  ['Inbetriebnahme', 'Commissioning'], ['nach Zieljahr', 'by target year'], ['Kennzahlen', 'Key figures'],
  ['Projektgröße', 'project size'], ['Nächste Schritte', 'Next steps'], ['NDA zeichnen', 'Execute NDA'],
  ['Shortlist festlegen', 'Define shortlist'], ['Datenraum und Prüfung', 'Data room and review'],
  ['Indikatives Angebot', 'Indicative offer'], ['Geschäftsführer', 'Managing Director'], ['n. v.', 'n/a'],
];

export function localizeProjectListHtml(html: string, language: ProjectListLanguage): string {
  if (language === 'de') return html;
  const withLanguage = html.replace('lang="de"', 'lang="en"');
  const styleMatch = withLanguage.match(/<style>[\s\S]*?<\/style>/);
  const style = styleMatch?.[0] ?? '';
  const body = style ? withLanguage.replace(style, '__EMA_STYLE__') : withLanguage;
  const replacements = [...englishReplacements]
    .filter(([source]) => source !== 'lang="de"')
    .sort(([a], [b]) => b.length - a.length);
  const escapeRegex = (value: string) => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const numberLocalized = body
    .split(/(<[^>]+>)/)
    .map((part) => part.startsWith('<')
      ? part
      : replacements.reduce((value, [source, target]) => {
          const prefix = /^[\p{L}\p{N}]/u.test(source) ? '(?<![\\p{L}\\p{N}])' : '';
          const suffix = /[\p{L}\p{N}]$/u.test(source) ? '(?![\\p{L}\\p{N}])' : '';
          return value.replace(new RegExp(`${prefix}${escapeRegex(source)}${suffix}`, 'gu'), target);
        }, part.replace(/\s+/g, ' '))
          .replace(/\b(\d{1,3})\.(?=\d{3}\b)/g, '$1§')
          .replace(/\b(\d+),(\d+)\b/g, '$1.$2')
          .replaceAll('§', ',')
          .replace(/\b(\d+)\. period\b/g, (_match, value: string) => {
            const number = Number(value);
            const mod100 = number % 100;
            const suffix = mod100 >= 11 && mod100 <= 13 ? 'th' : number % 10 === 1 ? 'st' : number % 10 === 2 ? 'nd' : number % 10 === 3 ? 'rd' : 'th';
            return `${number}${suffix} period`;
          }))
    .join('');
  return style ? numberLocalized.replace('__EMA_STYLE__', style) : numberLocalized;
}

