'use client'

import { useMemo, useRef, useState } from 'react'
import { Eye, FileText, Folder, FolderOpen, Link2, Pencil, Plus, Share2, Trash2, Upload, X } from 'lucide-react'
import { useRouter } from 'next/navigation'
import { toast } from 'sonner'
import { createClient } from '@/lib/supabase/client'
import {
  archiveTemplateDocument,
  createDocumentFolder,
  createTemplateDocumentRecord,
  deleteDocumentFolder,
  getTemplateDocumentUrl,
  moveDocumentToFolder,
  renameTemplateDocument,
  saveDocumentAssignments,
  type DocumentEntityType,
} from '@/lib/actions/template-document.actions'
import { formatFileSize } from '@/lib/utils'
import { clearDocumentViewerMarker, markDocumentViewerOpen } from '@/lib/ema/appIntroNavigation'

const CATEGORIES = [['nda','NDA / Vertraulichkeit'],['anfrageformular','Anfrageformular'],['vollmacht','Vollmacht'],['checkliste','Checkliste'],['vertrag','Vertrag'],['sonstiges','Sonstiges']] as const

type TemplateDocument = { id:string; display_name:string; category:string; file_name:string; file_path:string; file_size_bytes:number|null; mime_type:string|null; created_at:string; folder_id:string|null }
type FolderItem = { id:string; name:string; created_at:string }
type EntityOption = { id:string; label:string; subtitle?:string|null }
type Assignment = { document_id:string; entity_type:DocumentEntityType; entity_id:string }
type Props = { userId:string; documents:TemplateDocument[]; folders:FolderItem[]; partners:EntityOption[]; investors:EntityOption[]; projects:EntityOption[]; assignments:Assignment[] }

export function TemplateDocumentsClient({ userId, documents, folders, partners, investors, projects, assignments }: Props) {
  const router = useRouter(); const supabase = createClient(); const inputRef = useRef<HTMLInputElement>(null)
  const [file,setFile]=useState<File|null>(null); const [displayName,setDisplayName]=useState(''); const [category,setCategory]=useState('sonstiges'); const [folderId,setFolderId]=useState(''); const [uploading,setUploading]=useState(false); const [busyId,setBusyId]=useState<string|null>(null)
  const [assigningDocument,setAssigningDocument]=useState<TemplateDocument|null>(null); const [selected,setSelected]=useState<Set<string>>(new Set()); const [activeFolder,setActiveFolder]=useState<string|null>(null); const [showNewFolder,setShowNewFolder]=useState(false); const [newFolderName,setNewFolderName]=useState('')
  const [renamingDocument,setRenamingDocument]=useState<TemplateDocument|null>(null); const [renameValue,setRenameValue]=useState('')
  const assignmentCounts=useMemo(()=>{const map=new Map<string,number>(); for(const item of assignments) map.set(item.document_id,(map.get(item.document_id)??0)+1); return map},[assignments])
  const visibleDocuments=activeFolder===null?documents:documents.filter((d)=>d.folder_id===activeFolder)
  const selectFile=(f:File)=>{if(f.size>50*1024*1024)return toast.error('Die Datei darf maximal 50 MB groß sein.'); setFile(f); setDisplayName(f.name.replace(/\.[^/.]+$/,''))}
  const upload=async()=>{if(!file)return; setUploading(true); const safe=file.name.replace(/[^a-zA-Z0-9._-]+/g,'_'); const path=`${userId}/${Date.now()}_${safe}`; try{const {error}=await supabase.storage.from('template-documents').upload(path,file,{cacheControl:'3600',upsert:false}); if(error)throw error; const result=await createTemplateDocumentRecord({displayName:displayName.trim()||file.name,category,fileName:file.name,filePath:path,fileSizeBytes:file.size,mimeType:file.type||'application/octet-stream',folderId:folderId||null}); if(result.error){await supabase.storage.from('template-documents').remove([path]); throw new Error(result.error)} toast.success('Dokument wurde gespeichert.'); setFile(null); setDisplayName(''); setCategory('sonstiges'); setFolderId(''); if(inputRef.current)inputRef.current.value=''; router.refresh()}catch(e){toast.error(e instanceof Error?e.message:'Upload fehlgeschlagen.')}finally{setUploading(false)}}
  const openDocument=async(d:TemplateDocument)=>{markDocumentViewerOpen(); const openedWindow=window.open('about:blank','_blank'); setBusyId(d.id); const result=await getTemplateDocumentUrl(d.file_path); setBusyId(null); if(result.error||!result.url){openedWindow?.close(); clearDocumentViewerMarker(); return toast.error(result.error||'Datei konnte nicht geöffnet werden.')} if(openedWindow){openedWindow.opener=null; openedWindow.location.href=result.url}else{window.location.assign(result.url)}}
  const shareDocument=async(d:TemplateDocument)=>{setBusyId(d.id); try{const result=await getTemplateDocumentUrl(d.file_path); if(result.error||!result.url)throw new Error(result.error||'Datei konnte nicht geladen werden.'); const response=await fetch(result.url); if(!response.ok)throw new Error('Datei konnte nicht geladen werden.'); const blob=await response.blob(); const file=new File([blob],d.file_name,{type:d.mime_type||blob.type||'application/octet-stream'}); if(typeof navigator.share==='function'&&(!navigator.canShare||navigator.canShare({files:[file]}))){await navigator.share({title:d.display_name,files:[file]}); return} const url=URL.createObjectURL(file); const link=document.createElement('a'); link.href=url; link.download=file.name; link.click(); window.setTimeout(()=>URL.revokeObjectURL(url),60_000)}catch(error){if(error instanceof DOMException&&error.name==='AbortError')return; toast.error(error instanceof Error?error.message:'Dokument konnte nicht geteilt werden.')}finally{setBusyId(null)}}
  const archive=async(d:TemplateDocument)=>{if(!window.confirm(`„${d.display_name}“ entfernen?`))return; setBusyId(d.id); const result=await archiveTemplateDocument(d.id); setBusyId(null); if(result.error)return toast.error(result.error); router.refresh()}
  const openRename=(d:TemplateDocument)=>{setRenamingDocument(d); setRenameValue(d.display_name)}
  const saveRename=async()=>{if(!renamingDocument)return; setBusyId(renamingDocument.id); const result=await renameTemplateDocument(renamingDocument.id,renameValue); setBusyId(null); if(result.error)return toast.error(result.error); toast.success('Dokument wurde umbenannt.'); setRenamingDocument(null); setRenameValue(''); router.refresh()}
  const openAssignments=(d:TemplateDocument)=>{setAssigningDocument(d); setSelected(new Set(assignments.filter((a)=>a.document_id===d.id).map((a)=>`${a.entity_type}:${a.entity_id}`)))}
  const toggle=(type:DocumentEntityType,id:string)=>setSelected((current)=>{const next=new Set(current); const key=`${type}:${id}`; next.has(key)?next.delete(key):next.add(key); return next})
  const saveAssignments=async()=>{if(!assigningDocument)return; const result=await saveDocumentAssignments({documentId:assigningDocument.id,assignments:Array.from(selected).map((key)=>{const [entityType,entityId]=key.split(':'); return {entityType:entityType as DocumentEntityType,entityId}})}); if(result.error)return toast.error(result.error); toast.success('Zuordnungen gespeichert.'); setAssigningDocument(null); router.refresh()}
  const addFolder=async()=>{const result=await createDocumentFolder(newFolderName); if(result.error)return toast.error(result.error); setNewFolderName(''); setShowNewFolder(false); toast.success('Ordner erstellt.'); router.refresh()}
  const move=async(documentId:string,target:string)=>{const result=await moveDocumentToFolder(documentId,target||null); if(result.error)return toast.error(result.error); toast.success('Dokument verschoben.'); router.refresh()}
  const removeFolder=async(folder:FolderItem)=>{if(!window.confirm(`Ordner „${folder.name}“ löschen? Dokumente bleiben erhalten.`))return; const result=await deleteDocumentFolder(folder.id); if(result.error)return toast.error(result.error); if(activeFolder===folder.id)setActiveFolder(null); router.refresh()}
  const group=(title:string,type:DocumentEntityType,options:EntityOption[])=><div><h3 className="mb-2 text-xs font-extrabold uppercase tracking-[.12em] text-slate-500">{title}</h3><div className="max-h-48 space-y-2 overflow-y-auto rounded-2xl border border-slate-200 p-3">{options.map((o)=><label key={`${type}:${o.id}`} className="flex items-center gap-3 rounded-xl px-2 py-2"><input type="checkbox" checked={selected.has(`${type}:${o.id}`)} onChange={()=>toggle(type,o.id)} className="h-4 w-4 accent-[#5CB800]"/><span className="min-w-0"><strong className="block truncate text-sm text-[#07142F]">{o.label}</strong>{o.subtitle&&<span className="block truncate text-xs text-muted-foreground">{o.subtitle}</span>}</span></label>)}</div></div>

  return <div className="space-y-6">
    <section className="rounded-[2rem] border border-slate-200 bg-white p-5 shadow-sm md:p-7">
      <div className="flex items-center gap-4"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#5CB800]/12 text-[#2F8A00]"><Upload className="h-6 w-6"/></span><div><h2 className="text-xl font-extrabold text-[#07142F]">Dokument hochladen</h2><p className="mt-1 text-sm text-muted-foreground">PDF, Word, Excel, PowerPoint oder Bilddatei bis 50 MB.</p></div></div>
      <button type="button" onClick={()=>inputRef.current?.click()} className="mt-5 w-full rounded-2xl border-2 border-dashed border-slate-200 bg-slate-50 px-5 py-8 text-center"><FolderOpen className="mx-auto h-9 w-9 text-[#2F8A00]"/><strong className="mt-3 block text-sm text-[#07142F]">{file?file.name:'Datei auswählen'}</strong><span className="mt-1 block text-xs text-muted-foreground">oder hier ablegen</span></button>
      <input ref={inputRef} type="file" className="hidden" onChange={(e)=>{const f=e.target.files?.[0]; if(f)selectFile(f)}}/>
      {file&&<div className="mt-4 grid gap-4 md:grid-cols-3"><input className="form-input" value={displayName} onChange={(e)=>setDisplayName(e.target.value)} placeholder="Bezeichnung"/><select className="form-input" value={category} onChange={(e)=>setCategory(e.target.value)}>{CATEGORIES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select className="form-input" value={folderId} onChange={(e)=>setFolderId(e.target.value)}><option value="">Kein Ordner</option>{folders.map((f)=><option key={f.id} value={f.id}>{f.name}</option>)}</select><button onClick={upload} disabled={uploading} className="btn-primary md:col-span-3">{uploading?'Wird hochgeladen…':'Dokument speichern'}</button></div>}
    </section>

    <section className="rounded-[2rem] border border-slate-200 bg-white p-5 shadow-sm md:p-7">
      <div className="mb-5 flex items-center justify-between"><div><h2 className="text-xl font-extrabold text-[#07142F]">Ordner</h2><p className="mt-1 text-sm text-muted-foreground">{folders.length} Ordner</p></div><button onClick={()=>setShowNewFolder(true)} className="inline-flex items-center gap-2 text-sm font-extrabold text-[#2F8A00]"><Plus className="h-5 w-5"/> Neuer Ordner</button></div>
      <div className="grid gap-3 sm:grid-cols-2 md:grid-cols-3"><button onClick={()=>setActiveFolder(null)} className={`flex items-center gap-3 rounded-2xl border p-4 text-left ${activeFolder===null?'border-[#5CB800] bg-[#5CB800]/5':'border-slate-200'}`}><FolderOpen className="h-6 w-6 text-[#2F8A00]"/><span><strong className="block text-[#07142F]">Alle Dokumente</strong><span className="text-xs text-muted-foreground">{documents.length} Dokumente</span></span></button>{folders.map((f)=><div key={f.id} className={`flex items-center gap-3 rounded-2xl border p-4 ${activeFolder===f.id?'border-[#5CB800] bg-[#5CB800]/5':'border-slate-200'}`}><button onClick={()=>setActiveFolder(f.id)} className="flex min-w-0 flex-1 items-center gap-3 text-left"><Folder className="h-6 w-6 shrink-0 text-[#2F8A00]"/><span className="min-w-0"><strong className="block truncate text-[#07142F]">{f.name}</strong><span className="text-xs text-muted-foreground">{documents.filter((d)=>d.folder_id===f.id).length} Dokumente</span></span></button><button onClick={()=>removeFolder(f)} className="text-slate-400"><Trash2 className="h-4 w-4"/></button></div>)}</div>
    </section>

    <section className="rounded-[2rem] border border-slate-200 bg-white p-5 shadow-sm md:p-7"><div className="mb-5"><h2 className="text-xl font-extrabold text-[#07142F]">Gespeicherte Dokumente</h2><p className="mt-1 text-sm text-muted-foreground">{visibleDocuments.length} Dokument{visibleDocuments.length===1?'':'e'}</p></div><div className="space-y-3">{visibleDocuments.map((d)=>{const count=assignmentCounts.get(d.id)??0; return <div key={d.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-start gap-3"><FileText className="mt-1 h-6 w-6 shrink-0 text-[#1F2A44]"/><button onClick={()=>openDocument(d)} className="min-w-0 flex-1 text-left"><p className="whitespace-normal break-words font-extrabold leading-snug text-[#07142F]">{d.display_name}</p><p className="mt-1 text-xs text-muted-foreground">{d.file_size_bytes?formatFileSize(d.file_size_bytes):d.file_name}</p><p className="mt-1 text-xs font-bold text-[#2F8A00]">{count===0?'Noch nicht zugeordnet':`${count} Zuordnung${count===1?'':'en'}`}</p></button><button onClick={()=>openRename(d)} className="btn-icon shrink-0 text-slate-400 hover:text-[#2F8A00]" aria-label="Dokument umbenennen"><Pencil className="h-5 w-5"/></button><button onClick={()=>shareDocument(d)} disabled={busyId===d.id} className="btn-icon shrink-0 text-[#1F2A44]" aria-label="Dokument teilen"><Share2 className="h-5 w-5"/></button><button onClick={()=>openDocument(d)} disabled={busyId===d.id} className="btn-icon shrink-0 text-[#2F8A00]" aria-label="Dokument ansehen"><Eye className="h-5 w-5"/></button><button onClick={()=>archive(d)} className="btn-icon shrink-0 text-slate-400" aria-label="Entfernen"><Trash2 className="h-5 w-5"/></button></div><div className="mt-3 flex gap-2"><button onClick={()=>openAssignments(d)} className="inline-flex flex-1 items-center justify-center gap-2 rounded-xl bg-[#1F2A44] px-4 py-2.5 text-sm font-extrabold text-white"><Link2 className="h-4 w-4"/> Zuordnen</button><select value={d.folder_id??''} onChange={(e)=>move(d.id,e.target.value)} className="form-input max-w-[45%]"><option value="">Kein Ordner</option>{folders.map((f)=><option key={f.id} value={f.id}>{f.name}</option>)}</select></div></div>})}</div></section>

    {showNewFolder&&<div className="fixed inset-0 z-[100] flex items-end justify-center bg-black/45 p-3 md:items-center"><div className="w-full max-w-md rounded-[2rem] bg-white p-5"><div className="flex items-center justify-between"><h2 className="text-xl font-extrabold text-[#07142F]">Neuer Ordner</h2><button onClick={()=>setShowNewFolder(false)} className="btn-icon"><X className="h-5 w-5"/></button></div><input autoFocus value={newFolderName} onChange={(e)=>setNewFolderName(e.target.value)} className="form-input mt-5" placeholder="z. B. Verträge"/><button onClick={addFolder} className="btn-primary mt-4 w-full">Ordner erstellen</button></div></div>}
    {renamingDocument&&<div className="fixed inset-0 z-[100] flex items-end justify-center bg-black/45 p-3 md:items-center"><div className="w-full max-w-md rounded-[2rem] bg-white p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[.12em] text-[#2F8A00]">Dokument</p><h2 className="mt-1 text-xl font-extrabold text-[#07142F]">Umbenennen</h2></div><button onClick={()=>{setRenamingDocument(null); setRenameValue('')}} className="btn-icon"><X className="h-5 w-5"/></button></div><input autoFocus maxLength={160} value={renameValue} onChange={(e)=>setRenameValue(e.target.value)} onKeyDown={(e)=>{if(e.key==='Enter'&&renameValue.trim())void saveRename()}} className="form-input mt-5" placeholder="Dokumentname"/><p className="mt-2 text-xs text-muted-foreground">Der Inhalt und die Originaldatei bleiben unverändert.</p><div className="mt-5 flex gap-3"><button onClick={()=>{setRenamingDocument(null); setRenameValue('')}} className="btn-secondary flex-1">Abbrechen</button><button onClick={saveRename} disabled={!renameValue.trim()||busyId===renamingDocument.id} className="btn-primary flex-1">{busyId===renamingDocument.id?'Wird gespeichert…':'Speichern'}</button></div></div></div>}
    {assigningDocument&&<div className="fixed inset-0 z-[100] flex items-end justify-center bg-black/45 p-3 md:items-center"><div className="max-h-[88vh] w-full max-w-2xl overflow-y-auto rounded-[2rem] bg-white p-5"><div className="flex justify-between"><h2 className="text-2xl font-extrabold text-[#07142F]">{assigningDocument.display_name}</h2><button onClick={()=>setAssigningDocument(null)} className="btn-icon"><X className="h-5 w-5"/></button></div><div className="mt-5 grid gap-5 md:grid-cols-3">{group('Partner','partner',partners)}{group('Investoren','investor',investors)}{group('Projekte','project',projects)}</div><button onClick={saveAssignments} className="btn-primary mt-6 w-full">Zuordnungen speichern</button></div></div>}
  </div>
}
