export const EMA_ASSISTANT_REALTIME_TOOLS = [
  { type: 'function', name: 'ema_remember', description: 'Speichert eine vom Nutzer ausdrücklich zum Merken bestimmte persönliche, nicht sensible Information dauerhaft. Erfolg bedeutet, dass der Server den Datenbankeintrag anschließend verifiziert hat.', parameters: { type: 'object', properties: { content: { type: 'string' } }, required: ['content'], additionalProperties: false } },
  { type: 'function', name: 'ema_recall', description: 'Durchsucht das persönliche Gedächtnis des angemeldeten Nutzers.', parameters: { type: 'object', properties: { query: { type: 'string' } }, required: ['query'], additionalProperties: false } },
  { type: 'function', name: 'ema_forget', description: 'Vergisst passende Informationen aus dem persönlichen Gedächtnis.', parameters: { type: 'object', properties: { query: { type: 'string' } }, required: ['query'], additionalProperties: false } },
  { type: 'function', name: 'ema_create_reminder', description: 'Legt eine persönliche Erinnerung an. due_at ist ISO-8601 mit Datum und Uhrzeit.', parameters: { type: 'object', properties: { title: { type: 'string' }, due_at: { type: 'string' } }, required: ['title', 'due_at'], additionalProperties: false } },
  { type: 'function', name: 'ema_list_reminders', description: 'Liest heutige und überfällige offene Erinnerungen.', parameters: { type: 'object', properties: {}, additionalProperties: false } },
  { type: 'function', name: 'ema_mail_previews', description: 'Liest aktuelle Outlook-E-Mail-Vorschauen zur Zusammenfassung.', parameters: { type: 'object', properties: { limit: { type: 'integer', minimum: 1, maximum: 20 } }, additionalProperties: false } },
  { type: 'function', name: 'ema_calendar', description: 'Liest Outlook-Kalendertermine und Teams-Besprechungen.', parameters: { type: 'object', properties: { start: { type: 'string' }, end: { type: 'string' } }, additionalProperties: false } },
  { type: 'function', name: 'ema_contacts', description: 'Sucht Outlook-Kontakte.', parameters: { type: 'object', properties: { query: { type: 'string' } }, required: ['query'], additionalProperties: false } },
] as const

export const EMA_ASSISTANT_INSTRUCTIONS = `\nPersönliche Assistenz:\n- Bei „Merke dir …“, „Speicher dir …“, „Behalte im Gedächtnis …“ oder einer sinngleichen ausdrücklichen Bitte MUSST du ema_remember aufrufen. Behaupte niemals, du hättest etwas gespeichert oder würdest es dir merken, bevor ema_remember success=true zurückgegeben hat.\n- Wenn ema_remember fehlschlägt, sage klar und kurz, dass das Speichern nicht funktioniert hat; bestätige es niemals als gespeichert.\n- Bei Fragen wie „Was weißt du über …?“, „Was hast du dir gemerkt?“ oder „Erinnerst du dich an …?“ MUSST du ema_recall nutzen und darfst keine Erinnerungen aus dem laufenden Gespräch als dauerhaft gespeichert ausgeben.\n- Bei „Vergiss …“ nutze ema_forget.\n- Bei „Erinnere mich …“ nutze ema_create_reminder. Interpretiere Datum und Uhrzeit in Europe/Berlin und übergib einen ISO-8601-Zeitpunkt.\n- Für heutige oder überfällige Aufgaben nutze ema_list_reminders.\n- Für neue Outlook-Mails nutze ema_mail_previews, für Termine/Teams ema_calendar und für Kontakte ema_contacts.\n- Passwörter, PINs, Tokens, API-Schlüssel und Bankdaten niemals speichern.\n- Einen persönlichen Kalendertermin ohne weitere Teilnehmer darf EMA auf ausdrücklichen Sprachbefehl direkt im Kalender anlegen.\n- Sobald ein Termin oder eine Teams-Besprechung andere Teilnehmer enthält und dadurch Einladungen oder Nachrichten nach außen versendet werden, muss EMA vor dem Versand eine separate ausdrückliche Bestätigung des Nutzers einholen.\n- E-Mails dürfen ebenfalls erst nach separater ausdrücklicher Bestätigung versendet werden.\n- EMA darf niemals eigenständig Empfänger oder Teilnehmer ergänzen.`
