'use client'

import type { DataCenterImport } from '@/lib/ai/data-center-import'

const inputClass = 'mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm font-bold text-[#07142F] outline-none focus:border-[#5CB800] focus:ring-2 focus:ring-[#5CB800]/15'

function Field({ name, label, value, unit }: { name: string; label: string; value: string | number | null; unit?: string }) {
  return <label className="block rounded-2xl border border-slate-200 bg-white p-3 shadow-sm"><span className="text-[10px] font-extrabold uppercase tracking-[0.14em] text-slate-500">{label}</span><div className="relative"><input name={name} defaultValue={value ?? ''} className={`${inputClass} ${unit ? 'pr-16' : ''}`} />{unit && <span className="absolute right-3 top-1/2 mt-0.5 -translate-y-1/2 text-xs font-bold text-slate-400">{unit}</span>}</div></label>
}

export function DataCenterImportPreview({ data }: { data: DataCenterImport }) {
  return <div className="space-y-5">
    <section><h3 className="mb-3 text-sm font-extrabold text-[#07142F]">Standort</h3><div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><Field name="project_name" label="Projektname" value={data.projectName} /><Field name="location_state" label="Bundesland" value={data.state} /><Field name="location_district" label="Landkreis" value={data.district} /><Field name="location_city" label="Stadt / Gemeinde / Ort" value={data.city} /><Field name="location_address" label="Straße / Flurstück" value={data.address} /><Field name="coordinates" label="GPS-Koordinaten" value={data.coordinates} /></div></section>
    <section><h3 className="mb-3 text-sm font-extrabold text-[#07142F]">Grundstück</h3><div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><Field name="land_area_ha" label="Grundstücksgröße" value={data.landAreaHa} unit="ha" /><Field name="land_cost" label="Grundstückskosten / Pacht" value={data.landCost} /><Field name="land_price_sqm" label="Preis" value={data.landPricePerSqm} unit="€/m²" /></div></section>
    <section><h3 className="mb-3 text-sm font-extrabold text-[#07142F]">Baurecht & Flächennutzung</h3><div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><Field name="current_use" label="Aktuelle Nutzung" value={data.currentUse} /><Field name="zoning" label="Nutzungsart" value={data.zoning} /><Field name="development_plan" label="Bebauungsplan" value={data.developmentPlan} /><Field name="data_center_permitted" label="Rechenzentrum zulässig" value={data.dataCenterPermitted} /><Field name="building_height" label="Gebäudehöhe" value={data.buildingHeight} /><Field name="sealed_area" label="Versiegelbare Fläche" value={data.sealedArea} /><Field name="special_requirements" label="Besondere Anforderungen" value={data.specialRequirements} /></div></section>
    <section><h3 className="mb-3 text-sm font-extrabold text-[#07142F]">Stromversorgung</h3><div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><Field name="hv_distance_m" label="Entfernung HV / UW" value={data.hvDistanceM} unit="m" /><Field name="hv_station" label="HV / UW Station" value={data.hvStation} /><Field name="available_power_mw" label="Verfügbare Anschlussleistung" value={data.availablePowerMw} unit="MW" /><Field name="grid_operator" label="Netzbetreiber" value={data.gridOperator} /></div></section>
    <section><h3 className="mb-3 text-sm font-extrabold text-[#07142F]">Glasfaser</h3><div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><Field name="fiber_distance_m" label="Entfernung Glasfasertrasse" value={data.fiberDistanceM} unit="m" /><Field name="fiber_provider" label="Anbieter / Netzbetreiber" value={data.fiberProvider} /><Field name="fiber_on_site" label="Auf Grundstück vorhanden / geplant" value={data.fiberOnSite} /></div></section>
    <section><h3 className="mb-3 text-sm font-extrabold text-[#07142F]">Ansprechpartner</h3><div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><Field name="contact_name" label="Name" value={data.contactName} /><Field name="contact_company" label="Unternehmen" value={data.contactCompany} /><Field name="contact_phone" label="Telefon" value={data.contactPhone} /><Field name="contact_email" label="E-Mail" value={data.contactEmail} /><Field name="form_date" label="Datum" value={data.formDate} /></div></section>
    <p className="rounded-2xl bg-slate-50 p-3 text-xs font-bold text-slate-500">Leere Felder wurden im Dokument nicht sicher erkannt. EMA ergänzt keine erfundenen Werte.</p>
  </div>
}
